"""The PraisonAI desktop engine.

Stdlib only, so it starts in milliseconds and adds nothing to the venv beyond
praisonaiagents itself. The shell spawns this, reads the announced port from
stdout, and the webview then talks to it directly over loopback HTTP -- tokens
never cross the Tauri IPC bridge, which is the one design point all four
reference apps converge on.
"""

import collections
import json
import os
import pathlib
import secrets
import sys
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

# The shell matches this exact prefix. Printed once, after the socket is bound,
# so a port announced here is always a port that is actually listening.
# Dev mode: prefer the checkout over any installed copy in site-packages.
# Without this the engine silently imports a *different* praisonaiagents than
# the one being edited -- the same source/installed-copy divergence that makes
# a fix appear to have no effect. Explicit and visible here rather than via
# PYTHONPATH, which would follow every child process invisibly.
_SOURCE = pathlib.Path(__file__).resolve().parents[2] / "praisonai-agents"
if (_SOURCE / "praisonaiagents" / "__init__.py").is_file():
    sys.path.insert(0, str(_SOURCE))


PORT_MARKER = "PRAISONAI_PORT="
PROTOCOL_VERSION = 2

# Transcripts live outside the app bundle, in the user's own space, so an app
# update can never take them with it. Append-only JSON per conversation: the
# format a user can read, diff and back up without our help.
DATA_DIR = pathlib.Path(
    os.environ.get("PRAISONAI_DESKTOP_HOME")
    or (pathlib.Path.home() / "Library/Application Support/PraisonAI")
)
CHATS_DIR = DATA_DIR / "chats"


def _chat_path(cid: str) -> pathlib.Path:
    # Ids are generated by us, but a traversal attempt must not escape the dir.
    safe = "".join(c for c in cid if c.isalnum() or c in "-_")[:64]
    if not safe:
        raise ValueError("invalid conversation id")
    return CHATS_DIR / f"{safe}.json"


def load_chat(cid: str) -> dict:
    try:
        return json.loads(_chat_path(cid).read_text())
    except (OSError, ValueError):
        # Absent and corrupt are answered the same way here on purpose: the
        # caller is opening a conversation, and either way there is nothing to
        # show. The distinction is preserved in list_chats(), which reports a
        # corrupt file rather than hiding it.
        return {"id": cid, "title": "New chat", "messages": []}


def save_chat(chat: dict) -> None:
    CHATS_DIR.mkdir(parents=True, exist_ok=True)
    path = _chat_path(chat["id"])
    # Write-then-rename, so a crash mid-write cannot truncate an existing
    # transcript -- the failure mode that turns "my history is gone" into a
    # support ticket.
    tmp = path.with_suffix(".tmp")
    tmp.write_text(json.dumps(chat, indent=1))
    tmp.replace(path)


def list_chats() -> list:
    if not CHATS_DIR.is_dir():
        return []
    out = []
    for f in CHATS_DIR.glob("*.json"):
        try:
            c = json.loads(f.read_text())
            out.append({
                "id": c.get("id", f.stem),
                "title": c.get("title") or "New chat",
                "updated": c.get("updated", 0),
                "count": len(c.get("messages", [])),
                "project": c.get("project", ""),
            })
        except (OSError, ValueError):
            # Surfaced, not swallowed: a corrupt transcript the user can see is
            # recoverable; one silently omitted looks like data loss.
            out.append({"id": f.stem, "title": "(unreadable)", "updated": 0,
                        "count": 0, "corrupt": True})
    return sorted(out, key=lambda c: c["updated"], reverse=True)

_agent_lock = threading.Lock()
_agents = {}

# Run id -> cancellation flag. A cancelled run must stop *emitting*; we cannot
# interrupt the provider call itself from here, so cancellation is enforced at
# the yield boundary and the client is told the run ended early rather than
# being left to infer it from silence.
# --- tool approval -----------------------------------------------------------
# Every request carries call_id. Binding an approval to a row by position --
# "the one pending tool must be the one that asked" -- holds only while exactly
# one approval is ever outstanding, and silently authorises the wrong command
# the moment that stops being true.
_approval_lock = threading.Condition()
_approvals = {}          # approval_id -> {"call_id","name","args","decision"}
_always_allow = set()    # tool names the user granted for this process

APPROVAL_TIMEOUT_S = 300


def _await_decision(aid: str) -> str:
    """Block until the user decides. Returns 'allow' or 'deny'.

    Times out into 'deny': silence is not consent, and a run that hangs forever
    on an unanswered prompt is worse than one that stops.
    """
    deadline = time.time() + float(load_settings().get("approval_timeout",
                                                       APPROVAL_TIMEOUT_S))
    with _approval_lock:
        while _approvals[aid]["decision"] is None:
            if not _approval_lock.wait(timeout=max(0.1, deadline - time.time())):
                if time.time() >= deadline:
                    _approvals[aid]["decision"] = "deny"
                    break
        return _approvals.pop(aid)["decision"]


def resolve_approval(approval_id: str, choice: str) -> bool:
    """Record a decision. Returns False for an unknown id rather than pretending."""
    with _approval_lock:
        entry = _approvals.get(approval_id)
        if entry is None or entry["decision"] is not None:
            return False
        if choice == "always":
            _always_allow.add(entry["name"])
            choice = "allow"
        entry["decision"] = "allow" if choice == "allow" else "deny"
        _approval_lock.notify_all()
        return True


_cancel_lock = threading.Lock()
_cancelled = set()
_active_runs = set()


def cancel_run(run_id: str) -> bool:
    """Mark a run cancelled. Returns whether the run was actually live.

    Reporting success for an unknown id would be a lie the UI cannot detect:
    the button would confirm a cancellation that never happened.
    """
    with _cancel_lock:
        if run_id not in _active_runs:
            return False
        _cancelled.add(run_id)
    return True


def _is_cancelled(run_id: str) -> bool:
    with _cancel_lock:
        return run_id in _cancelled


def _forget(run_id: str) -> None:
    with _cancel_lock:
        _cancelled.discard(run_id)


# Tool events are not carried on the token stream, so we subscribe to the
# library's public display-callback hook instead of patching it. The callback
# fires on the worker thread running the turn, so events are parked in a
# thread-local queue and drained by the SSE loop that owns the socket -- writing
# to the response from a callback thread would interleave frames.
# Bounded ring: enough to explain the last few turns, small enough that it can
# never become the memory leak it exists to help diagnose.
_LOG = collections.deque(maxlen=400)


def log(line: str) -> None:
    _LOG.append(f"{time.strftime('%H:%M:%S')}  {line}")


_tool_events = threading.local()


def _set_emitter(fn):
    """The tool runs on the thread that owns the socket, so a gate can write its
    own frame. Queueing it instead would deadlock: the drain loop that would
    send it is downstream of the blocking call.

    Must be cleared when the turn ends. ThreadingHTTPServer reuses threads, so a
    leftover emitter belongs to a previous request's closed socket -- the next
    turn on that thread then writes into it and dies silently.
    """
    _tool_events.emit = fn


def _emit_now(event, payload):
    fn = getattr(_tool_events, "emit", None)
    if fn is not None:
        fn(event, payload)


def _tool_queue():
    q = getattr(_tool_events, "q", None)
    if q is None:
        q = _tool_events.q = []
    return q


def _on_tool_call(message=None, console=None, tool_name=None, tool_input=None,
                  tool_output=None, elapsed_time=None, success=True, **_):
    """Called by praisonaiagents when a tool completes."""
    _tool_queue().append({
        "call_id": f"c_{len(_tool_queue())}_{tool_name or 'tool'}",
        "name": tool_name or "tool",
        "args": tool_input or {},
        "output": "" if tool_output is None else str(tool_output),
        "ok": bool(success),
        "seconds": round(elapsed_time, 2) if isinstance(elapsed_time, (int, float)) else None,
    })


_callbacks_registered = False


def _ensure_callbacks():
    global _callbacks_registered
    if _callbacks_registered:
        return
    try:
        from praisonaiagents.main import register_display_callback

        register_display_callback("tool_call", _on_tool_call)
        _callbacks_registered = True
    except Exception:  # noqa: BLE001 - tool cards are a nicety, chat is not
        pass


def _builtin_tools():
    """Tools the desktop agent ships with.

    Deliberately few and safe: read-only, no shell, no writes. Anything with
    side effects waits until the approval gate exists -- shipping a tool the
    user cannot refuse is the wrong order to build in.
    """

    def _gate(name, args):
        """Ask the user before a filesystem read. Returns True when allowed."""
        mode = load_settings().get("approval_mode", "ask")
        if mode == "never" or name in _always_allow:
            return True
        if getattr(_tool_events, "emit", None) is None:
            # No stream to ask on. Blocking here would hang the turn for the
            # full timeout with nobody able to answer, so refuse instead --
            # a declined tool is recoverable, a frozen turn is not.
            log(f"gate {name}: no stream to ask on, declining")
            return False
        log(f"gate {name}: awaiting approval")
        cid = f"c_{secrets.token_urlsafe(6)}"
        aid = f"ap_{secrets.token_urlsafe(12)}"
        with _approval_lock:
            _approvals[aid] = {"call_id": cid, "name": name, "args": args, "decision": None}
        _emit_now("approval_request",
                  {"approval_id": aid, "call_id": cid, "name": name, "args": args})
        return _await_decision(aid) == "allow"

    def read_file(path: str) -> str:
        """Read a UTF-8 text file and return its contents.

        Args:
            path: Absolute or ~-relative path to the file.
        """
        import pathlib as _p

        if not _gate("read_file", {"path": path}):
            return "The user declined this tool call."
        f = _p.Path(path).expanduser()
        if not f.is_file():
            return f"No such file: {f}"
        if f.stat().st_size > 200_000:
            return f"File too large ({f.stat().st_size} bytes); read a smaller file."
        return f.read_text(errors="replace")

    def list_directory(path: str = ".") -> str:
        """List the entries in a directory.

        Args:
            path: Directory to list.
        """
        import pathlib as _p

        if not _gate("list_directory", {"path": path}):
            return "The user declined this tool call."
        d = _p.Path(path).expanduser()
        if not d.is_dir():
            return f"Not a directory: {d}"
        entries = sorted(d.iterdir(), key=lambda e: (not e.is_dir(), e.name))[:200]
        return "\n".join(("d " if e.is_dir() else "f ") + e.name for e in entries) or "(empty)"

    def web_search(query: str) -> str:
        """Search the web and return the top results.

        Args:
            query: What to search for.
        """
        import json as _j
        import urllib.parse as _u
        import urllib.request as _r

        key = os.environ.get("TAVILY_API_KEY")
        if not key:
            # Say what is missing rather than returning an empty result set that
            # the model would report as "I found nothing".
            return ("Web search is not configured. Set TAVILY_API_KEY in the "
                    "environment to enable it.")
        try:
            req = _r.Request(
                "https://api.tavily.com/search",
                data=_j.dumps({"api_key": key, "query": query,
                               "max_results": 5}).encode(),
                headers={"content-type": "application/json"},
            )
            with _r.urlopen(req, timeout=20) as resp:
                data = _j.loads(resp.read())
        except Exception as exc:  # noqa: BLE001 - the model must see the cause
            return f"Web search failed: {type(exc).__name__}: {exc}"
        rows = [f"- {r.get('title','')}\n  {r.get('url','')}\n  {r.get('content','')[:200]}"
                for r in (data.get("results") or [])]
        return "\n".join(rows) or "No results."

    def fetch_url(url: str) -> str:
        """Fetch a web page and return its text.

        Args:
            url: An http(s) URL.
        """
        import re as _re
        import urllib.request as _r

        if not url.startswith(("http://", "https://")):
            return "Only http and https URLs are supported."
        if not _gate("fetch_url", {"url": url}):
            return "The user declined this tool call."
        try:
            with _r.urlopen(url, timeout=20) as resp:
                body = resp.read(400_000).decode("utf-8", "replace")
        except Exception as exc:  # noqa: BLE001
            return f"Fetch failed: {type(exc).__name__}: {exc}"
        text = _re.sub(r"<script.*?</script>|<style.*?</style>", " ", body,
                       flags=_re.S | _re.I)
        text = _re.sub(r"<[^>]+>", " ", text)
        return _re.sub(r"\s+", " ", text).strip()[:20_000]

    def current_time() -> str:
        """Return the current local date and time."""
        import datetime as _dt

        return _dt.datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S %Z")

    return [read_file, list_directory, web_search, fetch_url, current_time]


APP_VERSION = "0.1.0"
SETTINGS_PATH = DATA_DIR / "settings.json"
MCP_PATH = DATA_DIR / "mcp.json"


def load_mcp() -> list:
    try:
        return json.loads(MCP_PATH.read_text()).get("servers", [])
    except (OSError, ValueError):
        return []


def save_mcp(servers: list) -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    tmp = MCP_PATH.with_suffix(".tmp")
    tmp.write_text(json.dumps({"servers": servers}, indent=1))
    tmp.replace(MCP_PATH)
# Mirrors frontend/dist/settings-registry.js. The registry is the source of
# truth for the UI; this is the storage contract, and load_settings() drops
# unknown keys and defaults missing ones so a hand-edited or older file can
# never leave the engine half-configured.
DEFAULT_SETTINGS = {
    "model": os.environ.get("PRAISONAI_MODEL", "gpt-4o-mini"),
    "temperature": 0.7,
    "max_tokens": 0,
    "top_p": 1,
    "base_url": "",
    "api_key": "",
    "system_prompt": "",
    "auto_title": True,
    "show_reasoning": True,
    "collapse_reasoning": False,
    "show_stats": True,
    "condense_paste": 4000,
    "theme": "system",
    "font_size": 15,
    "code_font_size": 12,
    "reduce_motion": "system",
    "approval_mode": "ask",
    "approval_timeout": 300,
    "confirm_delete": True,
    "launch_at_login": False,
    "check_updates": True,
}


# --- keychain ---------------------------------------------------------------
# Secrets go to the macOS keychain, never into settings.json. One reference app
# keyrings its API keys and then writes its proxy password to the settings file
# in plaintext -- the split is easy to get half-right, so it is centralised here.
KEYCHAIN_SERVICE = "ai.praison.desktop"
SECRET_KEYS = {"api_key"}


def keychain_set(name: str, value: str) -> bool:
    import subprocess
    try:
        if value:
            subprocess.run(["security", "add-generic-password", "-U",
                            "-s", KEYCHAIN_SERVICE, "-a", name, "-w", value],
                           check=True, capture_output=True, timeout=10)
        else:
            subprocess.run(["security", "delete-generic-password",
                            "-s", KEYCHAIN_SERVICE, "-a", name],
                           capture_output=True, timeout=10)
        return True
    except Exception:  # noqa: BLE001 - a keychain failure must not lose the turn
        return False


def keychain_get(name: str) -> str:
    import subprocess
    try:
        r = subprocess.run(["security", "find-generic-password",
                            "-s", KEYCHAIN_SERVICE, "-a", name, "-w"],
                           capture_output=True, timeout=10, text=True)
        return r.stdout.strip() if r.returncode == 0 else ""
    except Exception:  # noqa: BLE001
        return ""


def load_settings() -> dict:
    try:
        stored = json.loads(SETTINGS_PATH.read_text())
    except (OSError, ValueError):
        stored = {}
    # Unknown keys are dropped and missing keys defaulted, so a hand-edited or
    # older settings file can never leave the engine half-configured.
    out = {k: stored.get(k, v) for k, v in DEFAULT_SETTINGS.items()}
    for k in SECRET_KEYS:
        out[k] = keychain_get(k)
    return out


def save_settings(patch: dict) -> dict:
    merged = load_settings()
    for k in DEFAULT_SETTINGS:
        if k in patch:
            merged[k] = patch[k]
    for k in SECRET_KEYS:
        if k in patch:
            keychain_set(k, str(patch[k] or ""))
            merged[k] = patch[k]
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    tmp = SETTINGS_PATH.with_suffix(".tmp")
    # Secrets never reach the file.
    on_disk = {k: v for k, v in merged.items() if k not in SECRET_KEYS}
    tmp.write_text(json.dumps(on_disk, indent=1))
    tmp.replace(SETTINGS_PATH)
    # Settings change the agent's identity, so cached agents must go or the
    # next turn would silently run on the previous model.
    with _agent_lock:
        _agents.clear()
    return merged


def _llm_overrides(cfg: dict) -> dict:
    """Sampling overrides, passed at call time.

    Agent's constructor accepts none of temperature/max_tokens/top_p -- reaching
    them through llm={...} would switch to the custom-LLM path and pull in a
    134 MB dependency for identical intent. They are forwarded to start()
    instead, and only when the user actually changed them: sending
    temperature=0.7 unasked would override a provider default someone may have
    chosen deliberately elsewhere.
    """
    out = {}
    if cfg.get("temperature") != DEFAULT_SETTINGS["temperature"]:
        out["temperature"] = float(cfg["temperature"])
    if cfg.get("max_tokens"):
        out["max_tokens"] = int(cfg["max_tokens"])
    if cfg.get("top_p") != DEFAULT_SETTINGS["top_p"]:
        out["top_p"] = float(cfg["top_p"])
    _apply_env(cfg)
    return out


def _apply_env(cfg: dict) -> None:
    """Credentials and endpoint go to the environment, which the OpenAI client
    reads directly -- the constructor parameter routes through the heavier path.

    A cleared value must *remove* the variable, not be skipped: leaving a stale
    key or base_url in os.environ would keep routing subsequent turns to the
    credential or endpoint the user just deleted.
    """
    if cfg.get("base_url"):
        # Set as an env var rather than base_url=, which routes through a
        # heavier code path for identical intent.
        os.environ["OPENAI_API_BASE"] = cfg["base_url"]
    elif "base_url" in cfg:
        os.environ.pop("OPENAI_API_BASE", None)
    if cfg.get("api_key"):
        os.environ["OPENAI_API_KEY"] = cfg["api_key"]
    elif "api_key" in cfg:
        os.environ.pop("OPENAI_API_KEY", None)


def _get_agent(session_id: str = "default"):
    """One agent per session, built lazily: importing the engine costs more than
    binding a socket, and the window should be interactive before that is paid."""
    with _agent_lock:
        if session_id not in _agents:
            from praisonaiagents import Agent

            cfg = load_settings()
            _agents[session_id] = Agent(
                name="PraisonAI",
                role="Assistant",
                goal="Answer the user clearly and concisely.",
                instructions=cfg["system_prompt"] or None,
                llm=cfg["model"],
                tools=_builtin_tools(),
            )
        return _agents[session_id]


# --- stream protocol v2 -------------------------------------------------------
# v1 carried only start/delta/end/error, which is enough to print text and
# nothing else. Tool calls, reasoning and usage have to be first-class events or
# the UI has to infer them from prose -- and inference is how a tool call that
# silently failed still looks like a normal answer.
#
# Every event carries `msg_id` so the client can address a specific message
# rather than assuming the last one is the live one.
#
#   start        {msg_id}
#   reasoning    {msg_id, text}          incremental, collapsible
#   delta        {msg_id, text}          assistant text
#   tool_call    {msg_id, call_id, name, args}
#   tool_result  {msg_id, call_id, name, ok, output, seconds}
#   usage        {msg_id, chars, seconds, ttft}
#   cancelled    {msg_id, run_id}
#   error        {msg_id, message, kind}
#   end          {msg_id}

def _classify_stream_item(item):
    """Map one yielded item onto a protocol event.

    Returns (event, payload). Unrecognised shapes become text rather than being
    dropped: a client that renders an unexpected object badly is recoverable,
    one that silently discards it is not.
    """
    if isinstance(item, str):
        return "delta", {"text": item}
    if isinstance(item, dict):
        kind = item.get("type") or item.get("event")
        if kind in ("tool_call", "tool_use"):
            return "tool_call", {
                "call_id": str(item.get("id") or item.get("call_id") or ""),
                "name": item.get("name") or item.get("tool") or "tool",
                "args": item.get("args") or item.get("arguments") or {},
            }
        if kind in ("tool_result", "tool_output"):
            return "tool_result", {
                "call_id": str(item.get("id") or item.get("call_id") or ""),
                "name": item.get("name") or item.get("tool") or "tool",
                "ok": bool(item.get("ok", True)),
                "output": str(item.get("output") or item.get("result") or ""),
            }
        if kind in ("reasoning", "thinking", "reasoning_delta"):
            return "reasoning", {"text": str(item.get("text") or item.get("content") or "")}
        if "content" in item or "text" in item:
            return "delta", {"text": str(item.get("content") or item.get("text") or "")}
    return "delta", {"text": str(item)}


def _persist(chat_id: str, prompt: str, reply: list) -> None:
    """Append one exchange. Called only after a run completes, never per token --
    a per-token write is how a chat app burns through an SSD's write endurance."""
    try:
        chat = load_chat(chat_id)
        chat["id"] = chat_id
        chat["messages"].append({"role": "user", "content": prompt})
        chat["messages"].append({"role": "assistant", "content": "".join(reply)})
        if chat.get("title") in (None, "", "New chat"):
            chat["title"] = (prompt[:48] + "…") if len(prompt) > 48 else prompt
        chat["updated"] = int(time.time())
        save_chat(chat)
    except Exception:  # noqa: BLE001 - persistence must never break a reply
        pass


class Handler(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"

    def log_message(self, fmt, *args):  # noqa: A003 - quiet by default
        pass

    def _cors(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Headers", "content-type")

    def do_OPTIONS(self):
        self.send_response(204)
        self._cors()
        self.send_header("Content-Length", "0")
        self.end_headers()

    def _json(self, payload, status=200):
        body = json.dumps(payload).encode()
        self.send_response(status)
        self._cors()
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        if self.path == "/settings":
            self._json(load_settings())
            return
        if self.path == "/projects":
            names = sorted({(load_chat(c["id"]).get("project") or "")
                            for c in list_chats()} - {""})
            self._json({"projects": names})
            return
        if self.path == "/mcp":
            self._json({"servers": load_mcp()})
            return
        if self.path == "/update":
            # Honest: no release feed is wired yet, so say that rather than
            # reporting "up to date" for a check that never happened.
            self._json({"current": APP_VERSION, "checked": False,
                        "message": "Update checks are not configured yet."})
            return
        if self.path == "/logs":
            # The engine's own recent activity, so a user can see what happened
            # without leaving the app or finding a file.
            self._json({"lines": list(_LOG)})
            return
        if self.path.startswith("/search?"):
            from urllib.parse import parse_qs, urlparse
            q = (parse_qs(urlparse(self.path).query).get("q") or [""])[0].lower().strip()
            hits = []
            if q:
                for meta in list_chats():
                    chat = load_chat(meta["id"])
                    for m in chat.get("messages", []):
                        if q in str(m.get("content", "")).lower():
                            hits.append({"id": meta["id"], "title": meta["title"],
                                         "snippet": str(m.get("content"))[:120]})
                            break
            self._json({"hits": hits})
            return
        if self.path == "/chats":
            self._json({"chats": list_chats()})
            return
        if self.path.startswith("/chats/"):
            self._json(load_chat(self.path.rsplit("/", 1)[-1]))
            return
        if self.path != "/health":
            self.send_error(404)
            return
        # ok:true plus a version, so the supervisor can tell "engine healthy"
        # from "something else answered on this port".
        body = json.dumps({"ok": True, "version": PROTOCOL_VERSION}).encode()
        self.send_response(200)
        self._cors()
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_DELETE(self):
        if not self.path.startswith("/chats/"):
            self.send_error(404)
            return
        try:
            _chat_path(self.path.rsplit("/", 1)[-1]).unlink(missing_ok=True)
        except (OSError, ValueError):
            pass
        self._json({"ok": True})

    def do_POST(self):
        if self.path.startswith("/cancel/"):
            run_id = self.path.rsplit("/", 1)[-1]
            known = cancel_run(run_id)
            body = json.dumps({"ok": known, "run_id": run_id,
                               "error": None if known else "no such active run"}).encode()
            self.send_response(200 if known else 404)
            self._cors()
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return

        if self.path.startswith("/approve/"):
            aid = self.path.rsplit("/", 1)[-1]
            length = int(self.headers.get("Content-Length") or 0)
            try:
                choice = json.loads(self.rfile.read(length) or b"{}").get("choice", "deny")
            except (ValueError, TypeError):
                choice = "deny"   # a malformed body must never mean "allow"
            ok = resolve_approval(aid, choice)
            self._json({"ok": ok, "error": None if ok else "no such pending approval"},
                       200 if ok else 404)
            return

        if self.path == "/settings":
            length = int(self.headers.get("Content-Length") or 0)
            try:
                patch = json.loads(self.rfile.read(length) or b"{}")
            except (ValueError, TypeError):
                self.send_error(400)
                return
            self._json(save_settings(patch))
            return

        if self.path == "/mcp":
            length = int(self.headers.get("Content-Length") or 0)
            try:
                body = json.loads(self.rfile.read(length) or b"{}")
            except (ValueError, TypeError):
                self.send_error(400)
                return
            servers = load_mcp()
            action = body.get("action")
            if action == "add":
                name = str(body.get("name", "")).strip()
                if not name:
                    self._json({"ok": False, "error": "name is required"}, 400)
                    return
                servers = [x for x in servers if x.get("name") != name]
                servers.append({"name": name,
                                "command": str(body.get("command", "")),
                                "args": body.get("args") or [],
                                "enabled": bool(body.get("enabled", True))})
            elif action == "remove":
                servers = [x for x in servers if x.get("name") != body.get("name")]
            elif action == "toggle":
                for x in servers:
                    if x.get("name") == body.get("name"):
                        x["enabled"] = not x.get("enabled", True)
            else:
                self._json({"ok": False, "error": "unknown action"}, 400)
                return
            save_mcp(servers)
            self._json({"ok": True, "servers": servers})
            return

        if self.path.startswith("/fork/"):
            # Copy a transcript up to and including message N into a new chat,
            # leaving the original untouched -- a fork, not a rewrite.
            _, _, rest = self.path.partition("/fork/")
            cid, _, idx = rest.partition("/")
            try:
                src = load_chat(cid)
                n = int(idx) + 1
                new_id = f"{cid}-f{secrets.token_urlsafe(4)}"
                save_chat({"id": new_id,
                           "title": (src.get("title") or "New chat") + " (fork)",
                           "project": src.get("project", ""),
                           "messages": src.get("messages", [])[:n],
                           "updated": int(time.time())})
                self._json({"ok": True, "id": new_id})
            except (ValueError, KeyError):
                self._json({"ok": False, "error": "cannot fork"}, 404)
            return

        if self.path.startswith("/project/"):
            cid = self.path.rsplit("/", 1)[-1]
            length = int(self.headers.get("Content-Length") or 0)
            try:
                name = json.loads(self.rfile.read(length) or b"{}").get("project", "")
            except (ValueError, TypeError):
                name = ""
            chat = load_chat(cid)
            chat["id"] = cid
            chat["project"] = str(name)[:80]
            save_chat(chat)
            self._json({"ok": True, "project": chat["project"]})
            return

        if self.path.startswith("/messages/"):
            # Drop one exchange (a user turn and the reply it produced).
            _, _, rest = self.path.partition("/messages/")
            cid, _, idx = rest.partition("/")
            try:
                chat = load_chat(cid)
                i = int(idx)
                del chat["messages"][i:i + 2]
                save_chat(chat)
                self._json({"ok": True, "remaining": len(chat["messages"])})
            except (ValueError, IndexError, KeyError):
                self._json({"ok": False, "error": "no such message"}, 404)
            return

        if self.path == "/reset":
            length = int(self.headers.get("Content-Length") or 0)
            try:
                session = json.loads(self.rfile.read(length) or b"{}").get("session", "default")
            except (ValueError, TypeError):
                session = "default"
            with _agent_lock:
                _agents.pop(session, None)
            body = json.dumps({"ok": True}).encode()
            self.send_response(200)
            self._cors()
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return

        if self.path != "/chat":
            self.send_error(404)
            return
        length = int(self.headers.get("Content-Length") or 0)
        try:
            payload = json.loads(self.rfile.read(length) or b"{}")
            prompt = payload.get("prompt", "")
            run_id = str(payload.get("run_id") or "")
            session = payload.get("session", "default")
            chat_id = payload.get("chat_id") or session
            for att in (payload.get("attachments") or [])[:5]:
                nm = str(att.get("name", "file"))[:120]
                body = str(att.get("text", ""))[:100_000]
                prompt = f"{prompt}\n\n--- attached: {nm} ---\n{body}"
        except (ValueError, TypeError):
            self.send_error(400)
            return

        self.send_response(200)
        self._cors()
        self.send_header("Content-Type", "text/event-stream")
        self.send_header("Cache-Control", "no-cache")
        self.send_header("Connection", "close")
        self.end_headers()

        msg_id = f"m_{int(time.time()*1000):x}"

        def emit(event, data=None):
            payload = {"msg_id": msg_id, **(data or {})}
            self.wfile.write(f"event: {event}\ndata: {json.dumps(payload)}\n\n".encode())
            self.wfile.flush()

        if run_id:
            with _cancel_lock:
                _active_runs.add(run_id)
        started = time.perf_counter()
        first_token_at = None
        chars = 0
        reply = []
        tool_started = {}
        try:
            log(f"turn start chat={chat_id} run={run_id or '-'}")
            _set_emitter(emit)
            _ensure_callbacks()
            _tool_queue().clear()
            agent = _get_agent(session)
            emit("start", {"run_id": run_id})
            streamed = False
            def _emit_drafting(name):
                emit("tool_drafting", {"name": name})

            def _drain_tools():
                """Emit any tool activity recorded since the last check."""
                q = _tool_queue()
                while q:
                    ev = q.pop(0)
                    _emit_drafting(ev["name"])
                    emit("tool_call", {"call_id": ev["call_id"], "name": ev["name"],
                                       "args": ev["args"]})
                    log(f"tool {ev['name']} ok={ev['ok']} {ev.get('seconds')}s")
                    emit("tool_result", {"call_id": ev["call_id"], "name": ev["name"],
                                         "ok": ev["ok"], "output": ev["output"],
                                         "seconds": ev["seconds"]})

            for chunk in agent.start(prompt, stream=True,
                                     **_llm_overrides(load_settings())):
                _drain_tools()
                if run_id and _is_cancelled(run_id):
                    # Verified by side effect: emission stops. The client is told
                    # explicitly rather than inferring it from a stream that ends.
                    emit("cancelled", {"run_id": run_id})
                    break
                event, payload = _classify_stream_item(chunk)
                if event == "delta":
                    text = payload["text"]
                    if not text:
                        continue
                    if first_token_at is None:
                        first_token_at = time.perf_counter()
                    streamed = True
                    chars += len(text)
                    reply.append(text)
                    emit("delta", payload)
                elif event == "tool_call":
                    tool_started[payload["call_id"]] = time.perf_counter()
                    emit("tool_call", payload)
                elif event == "tool_result":
                    began = tool_started.pop(payload["call_id"], None)
                    if began is not None:
                        payload["seconds"] = round(time.perf_counter() - began, 2)
                    emit("tool_result", payload)
                else:
                    emit(event, payload)
            else:
                if not streamed:
                    # A stream that yielded nothing is a failure, not an empty answer.
                    emit("error", {"message": "the engine produced no output", "kind": "empty"})
                else:
                    _drain_tools()
                    elapsed = time.perf_counter() - started
                    _persist(chat_id, prompt, reply)
                    emit("usage", {
                        "chars": chars,
                        "seconds": round(elapsed, 2),
                        "ttft": round(first_token_at - started, 2) if first_token_at else None,
                    })
                    emit("end")
        except Exception as exc:  # noqa: BLE001 - the client must see the cause
            # `kind` lets the UI offer the right recovery: a missing key needs
            # settings, a rate limit needs retry, a bug needs the log.
            name = type(exc).__name__
            kind = ("auth" if "auth" in name.lower() or "key" in str(exc).lower()
                    else "rate_limit" if "rate" in str(exc).lower()
                    else "internal")
            log(f"ERROR {name}: {exc}")
            emit("error", {"message": f"{name}: {exc}", "kind": kind})
        finally:
            _set_emitter(None)
            _tool_queue().clear()
            if run_id:
                with _cancel_lock:
                    _active_runs.discard(run_id)
                _forget(run_id)


def main():
    # Port 0: the kernel assigns a free one, so a collision is impossible.
    server = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
    port = server.server_address[1]
    print(f"{PORT_MARKER}{port}", flush=True)
    print(f"praisonai runtime listening on 127.0.0.1:{port}", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    sys.exit(main())
