services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    volumes:
      - .:/app
    ports:
      - "8082:8082"
    environment:
      FLASK_ENV: development
      CHAINLIT_PORT: "8082"
      CHAINLIT_HOST: "0.0.0.0"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CHAINLIT_AUTH_SECRET: ${CHAINLIT_AUTH_SECRET}
    command: praisonai ui --host 0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082"]
      interval: 10s
      timeout: 5s
      retries: 3