#!/usr/bin/env python3
"""Example usage of HeyGen AI video generation tool with PraisonAI agents.

This example demonstrates how to use the HeyGen tool to create AI avatar videos
with PraisonAI agents. Set HEYGEN_API_KEY environment variable before running.

Usage:
    export HEYGEN_API_KEY="your_api_key_here"
    python example_heygen_usage.py
"""

import os
import time

def basic_heygen_usage():
    """Demonstrate basic HeyGen tool usage without agents."""
    print("🎬 Basic HeyGen Tool Usage")
    print("-" * 30)
    
    # Import HeyGen tools
    from praisonai_tools import heygen_list_avatars, heygen_list_voices, heygen_generate_video, heygen_video_status
    
    # Check if API key is set
    if not os.getenv("HEYGEN_API_KEY"):
        print("❌ HEYGEN_API_KEY environment variable not set")
        print("   Set it with: export HEYGEN_API_KEY='your_api_key'")
        return False
    
    try:
        # List available avatars
        print("📋 Listing available avatars...")
        avatars = heygen_list_avatars()
        print(f"   Found {len(avatars)} avatars")
        if avatars:
            first_avatar = avatars[0]
            print(f"   First avatar: {first_avatar.get('name', 'Unknown')} (ID: {first_avatar.get('id', 'Unknown')})")
        
        # List available voices  
        print("🎤 Listing available voices...")
        voices = heygen_list_voices()
        print(f"   Found {len(voices)} voices")
        if voices:
            first_voice = voices[0]
            print(f"   First voice: {first_voice.get('name', 'Unknown')} - {first_voice.get('language', 'Unknown')} (ID: {first_voice.get('id', 'Unknown')})")
        
        # Generate a video (this will cost credits!)
        print("🎯 Generating video...")
        script = "Hello! This is a test video generated by PraisonAI using the HeyGen API. The video generation is working perfectly!"
        
        result = heygen_generate_video(
            script=script,
            title="PraisonAI HeyGen Test Video"
        )
        
        video_id = result["video_id"]
        print(f"   Video generation started: {video_id}")
        
        # Check video status
        print("⏳ Checking video status...")
        status = heygen_video_status(video_id)
        print(f"   Status: {status['status']}")
        print(f"   Progress: {status.get('progress', 0)}%")
        
        if status['status'] == 'completed':
            print(f"✅ Video ready: {status.get('download_url', 'No URL')}")
        else:
            print("   Video is still processing. Check again later with:")
            print(f"   heygen_video_status('{video_id}')")
        
        return True
        
    except Exception as e:
        print(f"❌ Error: {e}")
        return False

def agent_heygen_usage():
    """Demonstrate HeyGen tool usage with PraisonAI agents."""
    print("\n🤖 Agent-Based HeyGen Usage")
    print("-" * 30)
    
    try:
        from praisonaiagents import Agent
        from praisonai_tools import heygen_list_avatars, heygen_list_voices, heygen_generate_video, heygen_video_status
        
        # Create an agent with HeyGen tools
        agent = Agent(
            name="Video Creator",
            instructions="""You are a professional AI video creator. 
            You help users create engaging AI avatar videos using HeyGen.
            Always list available avatars first, then generate videos with appropriate settings.
            Be helpful and provide clear status updates.""",
            tools=[heygen_list_avatars, heygen_list_voices, heygen_generate_video, heygen_video_status]
        )
        
        print("   Agent created successfully with HeyGen tools")
        print("   Tools available:", [tool.__name__ for tool in agent.tools if hasattr(tool, '__name__')])
        
        # Example prompt
        prompt = "Create a 30-second explainer video about PraisonAI multi-agent framework. First show me available avatars and voices."
        
        print(f"\n💬 Prompt: {prompt}")
        print("   (Note: This would make actual API calls and cost credits)")
        
        # Uncomment to actually run the agent:
        # result = agent.start(prompt)
        # print(f"🎬 Agent Result: {result}")
        
        return True
        
    except ImportError:
        print("❌ praisonaiagents not installed. Install with: pip install praisonaiagents")
        return False
    except Exception as e:
        print(f"❌ Error: {e}")
        return False

def main():
    """Main example runner."""
    print("🎥 HeyGen AI Video Generation Tool Example")
    print("=" * 50)
    
    # Run basic usage example
    basic_success = basic_heygen_usage()
    
    # Run agent usage example  
    agent_success = agent_heygen_usage()
    
    print("\n" + "=" * 50)
    if basic_success and agent_success:
        print("✅ All examples completed successfully!")
        print("\nNext steps:")
        print("1. Set your HEYGEN_API_KEY environment variable")
        print("2. Run agent.start() to actually generate videos")
        print("3. Use heygen_video_status() to check generation progress")
    else:
        print("❌ Some examples failed. Check the output above.")
    
    print("\n📚 More info: https://docs.heygen.com/reference/")

if __name__ == "__main__":
    main()