"""Shared primitives for sync & async schedulers."""

class ScheduleParser:
    """Shared schedule expression parser for both sync and async schedulers."""

    @staticmethod
    def parse(schedule_expr: str) -> int:
        """
        Parse schedule expression and return interval in seconds.

        Supported formats:
        - "daily" -> 86400 seconds
        - "hourly" -> 3600 seconds
        - "*/30m" -> 1800 seconds (every 30 minutes)
        - "*/1h" -> 3600 seconds (every 1 hour)
        - "60" -> 60 seconds (plain number)
        - "cron:M H * * *" -> best-effort interval from cron expression

        Args:
            schedule_expr: Schedule expression string

        Returns:
            Interval in seconds

        Raises:
            ValueError: If schedule format is not supported
        """
        expr = schedule_expr.strip().lower()

        if expr == "daily":
            return 86400
        if expr == "hourly":
            return 3600
        if expr.isdigit():
            return int(expr)
        if expr.startswith("*/"):
            part = expr[2:]
            if part.endswith("m"):
                return int(part[:-1]) * 60
            if part.endswith("h"):
                return int(part[:-1]) * 3600
            if part.endswith("s"):
                return int(part[:-1])
            return int(part)
        if expr.startswith("cron:"):
            return ScheduleParser._parse_cron_to_interval(expr[5:].strip())
        raise ValueError(f"Unsupported schedule format: {schedule_expr}")

    @staticmethod
    def _parse_cron_to_interval(cron_expr: str) -> int:
        """Convert a cron expression to a best-effort interval in seconds.

        Handles common cron patterns generated by the blueprint system:
        - ``"M H * * DOW"`` → 86400 (daily) if hour is fixed
        - ``"*/N * * * *"`` → N × 60 (every N minutes)
        - ``"M * * * *"`` → 3600 (hourly) if minute is fixed
        - Everything else → 60 (check every minute)
        """
        parts = cron_expr.split()
        if len(parts) != 5:
            return 60  # malformed cron → poll frequently

        minute, hour = parts[0], parts[1]

        # Interval-based: "*/15 * * * *" → every 15 minutes
        if minute.startswith("*/") and hour == "*":
            try:
                step = int(minute[2:])
                # Guard against "*/0" or negative steps which would yield a
                # non-positive interval and tight-loop the scheduler.
                return step * 60 if step > 0 else 60
            except ValueError:
                pass

        # Hourly: "30 * * * *" → run at minute 30 of every hour
        if minute.isdigit() and hour == "*":
            return 3600

        # Daily: "0 8 * * 1-5" or "0 8 * * *" → run at a specific hour daily
        if minute.isdigit() and hour.isdigit():
            return 86400

        # Fallback: poll every 60 seconds for complex patterns
        return 60


def backoff_delay(
    attempt: int,
    *,
    base: float = 2.0,
    initial: float = 30.0,
    cap: float = 300.0,
    jitter: float = 0.1,
) -> float:
    """Exponential backoff with jitter, capped. Used by both sync & async schedulers."""
    import random
    delay = min(max(initial, base ** attempt), cap)
    # Apply multiplicative jitter to avoid thundering herd
    return delay * random.uniform(1 - jitter, 1 + jitter)


def safe_call(cb, *args) -> None:
    """Run a user callback without letting it tear the scheduler down.

    Supports both sync and async callables. When called from a running event
    loop with a coroutine-returning callback, schedules it on the loop; when
    called from sync code, runs it via the shared persistent loop instead
    of creating + tearing down a fresh one per call.
    """
    if cb is None:
        return
    import logging
    import asyncio
    import inspect
    log = logging.getLogger(__name__)
    try:
        result = cb(*args)
        if inspect.iscoroutine(result):
            try:
                loop = asyncio.get_running_loop()
            except RuntimeError:
                # No loop here: dispatch to the shared persistent loop instead
                # of creating + tearing down a fresh one.
                try:
                    from .._async_bridge import run_sync
                    run_sync(result)
                except Exception as e:
                    log.error("Scheduler async callback raised: %s", e)
            else:
                # Running loop exists, schedule as task
                task = loop.create_task(result)
                task.add_done_callback(
                    lambda t: t.exception() and log.error(
                        "Scheduler async callback raised: %s", t.exception()
                    )
                )
    except Exception as e:
        log.error("Scheduler callback raised: %s", e)