"""
Suggestion Engine — proposes automation blueprints as consent-first suggestions.

This module provides the heavy implementation side of the suggestion
system.  It wraps :class:`~praisonaiagents.scheduler.suggestion_store.SuggestionStore`
to provide a higher-level API for proposing, listing, accepting, and
dismissing automation suggestions.

"Nothing is ever auto-created" — the engine only writes to the
SuggestionStore; only explicit user acceptance materializes a job.

Usage::

    from praisonai.scheduler.suggestion_engine import SuggestionEngine

    engine = SuggestionEngine()
    sug_id = engine.propose(
        "morning-brief",
        slots={"hour": 8, "weekdays": "mon-fri"},
        deliver="telegram",
        reason="Detected daily morning request pattern",
    )
    if sug_id:
        print(f"Suggestion created: {sug_id}")
"""

from __future__ import annotations

import logging
import time
import uuid
from typing import Any, Dict, List, Optional, Tuple

from praisonaiagents.scheduler.suggestion_store import (
    SuggestionStore,
    Suggestion,
    DEFAULT_TTL_SEC,
)

logger = logging.getLogger(__name__)

DEFAULT_RECURRENCE_THRESHOLD: int = 3
"""How many times the same intent must recur before it is auto-proposed."""

DEFAULT_RECURRENCE_WINDOW_SEC: float = 3600 * 24 * 7
"""Only occurrences within this trailing window count toward recurrence
(default: 7 days).  Older observations are pruned."""


def _freeze(value: Any) -> Any:
    """Return a deterministic, hashable representation of ``value``.

    Slots are typed ``Dict[str, Any]`` and the store accepts nested lists /
    dicts / sets, so the recurrence key must survive those too.  Plain
    ``tuple(sorted(items))`` raises ``TypeError`` on unhashable values; this
    recursively freezes dicts, lists/tuples, and sets so any JSON-shaped slot
    payload yields a stable, hashable key.
    """
    if isinstance(value, dict):
        return tuple(sorted((k, _freeze(v)) for k, v in value.items()))
    if isinstance(value, (list, tuple)):
        return tuple(_freeze(v) for v in value)
    if isinstance(value, (set, frozenset)):
        return tuple(sorted(_freeze(v) for v in value))
    return value


class SuggestionEngine:
    """Heuristic engine for proposing blueprint-based automations.

    Suggestions can be triggered two ways:

    * **Explicitly** via :meth:`propose` (CLI, dashboard, programmatic API).
    * **Automatically** via :meth:`observe`, a lightweight deterministic
      recurrence detector: a caller feeds each completed turn's inferred
      intent, and once the same intent recurs ``threshold`` times within a
      trailing window the engine calls :meth:`propose` itself. This is the
      generator that turns "you ask for a morning summary every day" into an
      offered automation.

    The engine enforces the consent-first rule: nothing is ever
    auto-created.  Every proposal — whether explicit or auto-generated by
    :meth:`observe` — must still be explicitly accepted before it becomes a
    real scheduled job. The underlying store's dedup + dismissal latching
    keeps auto-proposals non-nagging.
    """

    def __init__(self, store_path: Optional[str] = None):
        self._store = SuggestionStore(path=store_path)
        # Trailing observation log for the recurrence detector, keyed by the
        # intent identity (principal, blueprint, frozen-slots). Values are the
        # timestamps of recent occurrences within the recurrence window. This
        # is process-local, best-effort memory — the consent-first store is the
        # only durable state, so losing it merely resets the counter.
        self._observations: Dict[
            Tuple[Optional[str], str, Any], List[float]
        ] = {}

    # -- public API ------------------------------------------------------------

    def propose(
        self,
        blueprint_name: str,
        slots: Optional[Dict[str, Any]] = None,
        deliver: str = "",
        reason: str = "",
        ttl_seconds: float = DEFAULT_TTL_SEC,
        principal: Optional[str] = None,
    ) -> Optional[str]:
        """Propose a blueprint-based automation to the user.

        The proposal is added to the suggestion store, where it waits
        for the user to accept or dismiss.  This method does **not**
        create a schedule job — it only writes a suggestion.

        Args:
            blueprint_name: Name of the blueprint to suggest.
            slots: Pre-filled slot values.
            deliver: Suggested delivery target.
            reason: Human-readable explanation of why this is proposed.
            ttl_seconds: How long before the suggestion auto-expires
                (default: 3 days).  Use ``0`` for no expiry.
            principal: Resolved canonical identity of the owning end-user
                on a multi-user gateway. Stamped on the suggestion so
                :meth:`pending`/:meth:`accept`/:meth:`dismiss` isolate it
                per user. ``None`` (the default) keeps the global,
                single-tenant pool used by CLI / single-user deployments.

        Returns:
            The suggestion ID if the proposal was accepted by the store,
            ``None`` if rejected (cap full or duplicate).
        """
        sug = Suggestion(
            id=f"sug_{uuid.uuid4().hex[:12]}",
            blueprint_name=blueprint_name,
            slots=slots or {},
            deliver=deliver,
            reason=reason,
            created_at=time.time(),
            expires_at=(time.time() + ttl_seconds) if ttl_seconds > 0 else 0.0,
            principal=principal,
        )
        ok = self._store.add(sug)
        if ok:
            return sug.id
        logger.debug(
            "Suggestion for blueprint '%s' rejected (cap or dup)",
            blueprint_name,
        )
        return None

    def observe(
        self,
        blueprint_name: str,
        slots: Optional[Dict[str, Any]] = None,
        deliver: str = "",
        reason: str = "",
        principal: Optional[str] = None,
        threshold: int = DEFAULT_RECURRENCE_THRESHOLD,
        window_seconds: float = DEFAULT_RECURRENCE_WINDOW_SEC,
        ttl_seconds: float = DEFAULT_TTL_SEC,
    ) -> Optional[str]:
        """Record one occurrence of an intent and auto-propose on recurrence.

        This is the *generator* that lets the assistant offer an automation on
        its own. A caller (bot/gateway/CLI) feeds the blueprint+slots inferred
        from each completed turn; the engine counts distinct occurrences of the
        same intent within a trailing window and, once ``threshold`` is reached,
        calls :meth:`propose` exactly once. Consent-first is preserved — the
        proposal still only materialises a job on explicit ``accept`` — and the
        store's dedup + dismissal latching keeps it non-nagging.

        Args:
            blueprint_name: Blueprint the recurring intent maps to.
            slots: Slot values that identify the specific intent. The same
                blueprint with different slots is tracked as a distinct intent.
            deliver: Suggested delivery target, forwarded to :meth:`propose`.
            reason: Human-readable explanation; a sensible default is used when
                omitted.
            principal: Owning end-user identity on a multi-user gateway. Counts
                are isolated per principal.
            threshold: Occurrences required before auto-proposing (default 3).
            window_seconds: Trailing window in which occurrences count.
            ttl_seconds: TTL forwarded to :meth:`propose`.

        Returns:
            The new suggestion ID if this observation crossed the threshold and
            a proposal was created, otherwise ``None`` (still counting, below
            threshold, or the store rejected it as a cap/dup).
        """
        now = time.time()
        key = (
            principal,
            blueprint_name,
            _freeze(slots or {}),
        )

        # Append this occurrence and prune anything outside the window so a
        # count only ever reflects recent, still-relevant intent.
        cutoff = now - window_seconds if window_seconds > 0 else 0.0
        timestamps = [t for t in self._observations.get(key, []) if t >= cutoff]
        timestamps.append(now)
        self._observations[key] = timestamps

        if len(timestamps) < max(1, threshold):
            return None

        # Threshold reached: reset the counter so we don't re-fire every turn,
        # and let the store's dedup window guard against re-proposing. propose()
        # returns None on cap/dup, which is the desired non-nagging behaviour.
        self._observations[key] = []
        return self.propose(
            blueprint_name=blueprint_name,
            slots=slots,
            deliver=deliver,
            reason=reason or (
                f"Noticed a recurring '{blueprint_name}' request "
                f"({len(timestamps)}x); offering to automate it."
            ),
            ttl_seconds=ttl_seconds,
            principal=principal,
        )

    def pending(self, principal: Optional[str] = None) -> List[Suggestion]:
        """Return the list of pending (undismissed, unaccepted) suggestions.

        Args:
            principal: When given, only suggestions owned by this resolved
                identity are returned (multi-user gateway isolation).
                ``None`` returns the global pool (single-tenant behaviour).
        """
        return self._store.list_pending(principal)

    def accept(self, suggestion_id: str, principal: Optional[str] = None) -> bool:
        """Mark a suggestion as accepted.

        Args:
            suggestion_id: The suggestion to accept.
            principal: When given, the accept is refused unless the
                suggestion is owned by this identity, preventing one
                gateway user from accepting another's. ``None`` skips the
                ownership check (single-tenant behaviour).

        Note:
            This only updates the suggestion's status.  The caller is
            responsible for materializing the corresponding schedule job.
        """
        return self._store.accept(suggestion_id, principal)

    def dismiss(self, suggestion_id: str, principal: Optional[str] = None) -> bool:
        """Mark a suggestion as dismissed (user declined).

        Args:
            suggestion_id: The suggestion to dismiss.
            principal: When given, the dismiss is refused unless the
                suggestion is owned by this identity. ``None`` skips the
                ownership check (single-tenant behaviour).
        """
        return self._store.dismiss(suggestion_id, principal)

    def get_suggestion(self, suggestion_id: str) -> Optional[Suggestion]:
        """Return a single suggestion by ID, or ``None``."""
        return self._store.get(suggestion_id)
