# # -*- coding: utf-8 -*-
# """Praison_AI_Real_Estate_Chatbot.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1E06aeVop9cUqumuqKmF_beCRl_yF90pP

# # Praison AI Real Estate Chatbot

# Interact with a real estate AI assistant powered by PraisonAI and OpenAI.

# [![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/DhivyaBharathy-web/PraisonAI/blob/main/examples/cookbooks/Praison_AI_Real_Estate_Chatbot.ipynb)

# ## 1. Install Dependencies
# """

# !pip install praisonaiagents openai

# """## 2. Set Your OpenAI API Key"""

import os

# Enter your OpenAI API key here
OPENAI_API_KEY = "Enter your api key here"  # <-- Replace with your key
os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY

# """## 3. Create the Praison AI Agent"""

from praisonaiagents import Agent

praison_agent = Agent(
    name="Praison Real Estate Chatbot",
    role="Answer real estate questions and provide helpful advice.",
    instructions=[
        "You are a helpful real estate assistant.",
        "Answer user questions about buying, selling, or renting property.",
        "Provide clear, concise, and friendly advice."
    ],
    markdown=True
)

# """## 4. Chat with the Agent"""

import ipywidgets as widgets
from IPython.display import display, Markdown

def ask_agent(question):
    # Use the .chat() method for the public praisonaiagents package
    response = praison_agent.chat(question)
    display(Markdown(f"**Praison AI:** {response}"))

question = widgets.Text(
    value='',
    placeholder='Type your real estate question here...',
    description='You:',
    disabled=False
)
button = widgets.Button(description="Ask Praison AI")

def on_button_clicked(b):
    ask_agent(question.value)

button.on_click(on_button_clicked)
display(question, button)