"""
Template files for PraisonAI setup.

Contains .env, config.yaml, and agents.yaml templates.
"""

ENV_TEMPLATE = """# PraisonAI Configuration
# Generated by praisonai setup
#
# Uncomment and set the appropriate API key for your provider:

# OpenAI
# OPENAI_API_KEY=sk-your-openai-key-here

# Anthropic
# ANTHROPIC_API_KEY=sk-ant-your-anthropic-key-here

# Google
# GEMINI_API_KEY=your-gemini-key-here

# Other useful environment variables:
# PRAISONAI_DEBUG=1
# PRAISONAI_LOG_LEVEL=INFO
"""

CONFIG_TEMPLATE = """# PraisonAI Configuration
# Generated by praisonai setup

provider: openai
model: gpt-4o-mini
telemetry: true

# Advanced configuration options:
# temperature: 0.7
# max_tokens: 1000
# timeout: 30
"""

AGENTS_TEMPLATE = """# Starter PraisonAI Agents Configuration
# Generated by praisonai setup

agents:
  - name: "Assistant"
    instructions: "You are a helpful AI assistant. Be concise and accurate."
    llm: "gpt-4o-mini"
    
  - name: "Researcher" 
    instructions: "You are a research assistant. Find accurate information and cite sources."
    llm: "gpt-4o-mini"

tasks:
  - name: "greeting"
    description: "Say hello and introduce yourself"
    agent: "Assistant"
    
  - name: "research_task"
    description: "Research a topic provided by the user"
    agent: "Researcher"

# To run this workflow:
# praisonai workflow run --file agents.yaml
"""