import os
import re

target_dir = '/Users/praison/praisonai-package/src/praisonai-agents/praisonaiagents'

changed_files = 0
files_to_check = []

for root, dirs, files in os.walk(target_dir):
    for file in files:
        if file.endswith('.py') and file != '_logging.py' and not file.startswith('refactor_'):
            files_to_check.append(os.path.join(root, file))

for path in files_to_check:
    with open(path, 'r') as f:
        original_content = f.read()
    
    content = original_content

    # Look for logging.getLogger(
    if 'logging.getLogger' in content:
        print(f"Refactoring: {path}")

        # Safely insert the new import if it hasn't been added yet
        if 'from praisonaiagents._logging import get_logger' not in content:
            # Find a good place to insert it: Replace "import logging" if exists
            if 'import logging' in content:
                content = re.sub(r'import logging\n', 'import logging\nfrom praisonaiagents._logging import get_logger\n', content, count=1)
            else:
                # Fallback injection at top
                content = 'from praisonaiagents._logging import get_logger\n' + content
        
        # Replace logging.getLogger( -> get_logger(
        content = re.sub(r'logging\.getLogger\(', 'get_logger(', content)

    # Strip manual setLevel unless it's a specific logic block that explicitly changes it.
    content = re.sub(r'^[ \t]*logger\.setLevel\(logging\.[A-Z]+\)\s*$', '', content, flags=re.MULTILINE)
    content = re.sub(r'^[ \t]*logger\.addHandler\(logging\.StreamHandler\(\)\)\s*$', '', content, flags=re.MULTILINE)

    if content != original_content:
        # Final cleanup for empty lines generated by strip
        content = content.replace('\n\n\n', '\n\n')
        with open(path, 'w') as f:
            f.write(content)
        changed_files += 1

print(f"\nSuccessfully refactored {changed_files} files!")
