// The desktop dev binary, used only for `cargo tauri dev` while iterating on
// the shell logic. On iOS and Android the entry point is `start_app` /
// `Java_..._create`, generated by `#[tauri::mobile_entry_point]` in lib.rs —
// this `main` is never called there.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

fn main() {
    praisonai_mobile_lib::run()
}
