"""
Behaviour parity: options accepted for Python parity that are not yet acted on.

The other two layers measure PRESENCE. The name tracker asks whether an export
exists; the signature checker asks whether a parameter exists. An option that is
accepted, typed, documented and then ignored passes both -- which is how 76 of
them accumulated without any number moving.

This layer counts them. The source of truth is the `UNHONOURED_OPTIONS` ledger
in src/praisonai-ts/src/utils/parity-notice.ts, which the TypeScript surfaces
themselves iterate, so the count cannot drift from what the code does.

The gate is a ratchet: the committed report carries the total, and `--check`
fails if the current total is HIGHER. Closing an option lowers it; accepting a
new one without implementing it raises it and reddens the build. Regenerate with
`--write` when you close one.

    python -m praisonai._dev.parity.behaviour --write
    python -m praisonai._dev.parity.behaviour --check
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

from ._paths import find_repo_root

LEDGER = 'src/praisonai-ts/src/utils/parity-notice.ts'
MD_OUTPUT = 'src/praisonai-ts/BEHAVIOUR_PARITY.md'
JSON_OUTPUT = 'src/praisonai-ts/behaviour-parity.json'

# `notYetHonoured('Surface', 'option', 'why')` with literal arguments: an option
# that works for some inputs and not others. Counted apart from the ledger,
# because the option is not wholly absent.
_PARTIAL_RE = re.compile(r"notYetHonoured\(\s*'([^']+)'\s*,\s*'([^']+)'\s*,")
_SURFACE_RE = re.compile(r"^\s*'([^']+)':\s*\[(.*?)\]\s*,\s*$", re.S | re.M)
_OPTION_RE = re.compile(r"'([A-Za-z_][A-Za-z0-9_]*)'")


@dataclass
class Behaviour:
    """What the TypeScript SDK accepts but does not yet act on."""

    surfaces: Dict[str, List[str]] = field(default_factory=dict)
    partial: List[Dict[str, str]] = field(default_factory=list)

    @property
    def total(self) -> int:
        return sum(len(v) for v in self.surfaces.values())


class LedgerError(RuntimeError):
    """The ledger could not be read. Never reported as 'nothing left to do'."""


def _ledger_block(text: str) -> str:
    """The body of the UNHONOURED_OPTIONS object literal."""
    marker = 'export const UNHONOURED_OPTIONS'
    if marker not in text:
        raise LedgerError(
            f'{LEDGER} no longer declares {marker}. If it was renamed, update '
            'praisonai._dev.parity.behaviour to match -- a ledger this tool cannot '
            'read must never be reported as zero options outstanding.'
        )
    start = text.index(marker)
    open_brace = text.index('{', start)
    depth = 0
    for i in range(open_brace, len(text)):
        if text[i] == '{':
            depth += 1
        elif text[i] == '}':
            depth -= 1
            if depth == 0:
                return text[open_brace + 1:i]
    raise LedgerError(f'the UNHONOURED_OPTIONS literal in {LEDGER} is not closed')


def read_ledger(repo_root: Path) -> Behaviour:
    """Parse the ledger and the partial-case call sites out of the sources."""
    ledger_path = repo_root / LEDGER
    if not ledger_path.is_file():
        raise LedgerError(f'{LEDGER} not found; is --repo-root right?')
    body = _ledger_block(ledger_path.read_text(encoding='utf-8'))

    surfaces: Dict[str, List[str]] = {}
    for match in _SURFACE_RE.finditer(body):
        surfaces[match.group(1)] = _OPTION_RE.findall(match.group(2))
    if not surfaces:
        # Refuse to report "nothing left to do" because a regex stopped matching.
        raise LedgerError(f'no surfaces parsed from {LEDGER}; the ledger shape changed')

    partial: List[Dict[str, str]] = []
    src = repo_root / 'src/praisonai-ts/src'
    for path in sorted(src.rglob('*.ts')):
        if path.name == 'parity-notice.ts':
            continue
        for surface, option in _PARTIAL_RE.findall(path.read_text(encoding='utf-8')):
            partial.append({
                'surface': surface,
                'option': option,
                'file': str(path.relative_to(repo_root).as_posix()),
            })
    return Behaviour(surfaces=surfaces, partial=partial)


def render_markdown(b: Behaviour) -> str:
    lines = [
        '# Behaviour Parity: options accepted but not yet acted on',
        '',
        '<!-- Generated by `python -m praisonai._dev.parity.behaviour --write`. Do not edit by hand. -->',
        '',
        '## What this measures',
        '',
        'PARITY.md asks whether a name is exported. SIGNATURE_PARITY.md asks whether a',
        'parameter exists. Both pass for an option that is accepted and then ignored, so',
        'this file counts those: every option the TypeScript SDK takes for Python parity',
        'and does not yet act on. The source is the `UNHONOURED_OPTIONS` ledger in',
        '`src/praisonai-ts/src/utils/parity-notice.ts`, which the surfaces iterate at',
        'runtime, so the count cannot drift from the behaviour.',
        '',
        'The check is a ratchet: the total may fall, never rise.',
        '',
        '## Summary',
        '',
        '| Surface | Options not yet acted on |',
        '|---|---|',
    ]
    for surface in sorted(b.surfaces):
        lines.append(f'| `{surface}` | {len(b.surfaces[surface])} |')
    lines += [
        f'| **Total** | **{b.total}** |',
        '',
        f'Plus {len(b.partial)} options that work for some inputs and announce themselves for the rest.',
        '',
        '## The queue',
        '',
        'Each row is one unit of work: implement it, delete its entry from the ledger,',
        'add a test proving the option changes what the code does, and regenerate.',
        '',
    ]
    for surface in sorted(b.surfaces):
        options = b.surfaces[surface]
        if not options:
            continue
        lines += [f'### `{surface}` ({len(options)})', '']
        lines += [f'- `{option}`' for option in options]
        lines.append('')
    if b.partial:
        lines += ['## Partial', '', '| Surface | Option | Declared in |', '|---|---|---|']
        for row in sorted(b.partial, key=lambda r: (r['surface'], r['option'])):
            lines.append(f"| `{row['surface']}` | `{row['option']}` | `{row['file']}` |")
        lines.append('')
    return '\n'.join(lines)


def render_json(b: Behaviour) -> str:
    payload = {
        'total': b.total,
        'surfaces': {k: sorted(v) for k, v in sorted(b.surfaces.items())},
        'partial': sorted(b.partial, key=lambda r: (r['surface'], r['option'])),
    }
    return json.dumps(payload, indent=2, sort_keys=True) + '\n'


def committed_total(repo_root: Path) -> Optional[int]:
    path = repo_root / JSON_OUTPUT
    if not path.is_file():
        return None
    try:
        return int(json.loads(path.read_text(encoding='utf-8'))['total'])
    except (ValueError, KeyError, TypeError):
        return None


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[1])
    parser.add_argument('--write', action='store_true', help='regenerate the report')
    parser.add_argument('--check', action='store_true', help='fail if the report is stale or the total grew')
    parser.add_argument('--repo-root', type=Path, default=None)
    args = parser.parse_args(argv)

    repo_root = args.repo_root or find_repo_root()
    try:
        b = read_ledger(repo_root)
    except LedgerError as exc:
        print(f'behaviour parity: cannot read the ledger: {exc}', file=sys.stderr)
        return 2
    md, js = render_markdown(b), render_json(b)

    if args.write:
        (repo_root / MD_OUTPUT).write_text(md, encoding='utf-8')
        (repo_root / JSON_OUTPUT).write_text(js, encoding='utf-8')
        print(f'wrote {MD_OUTPUT} and {JSON_OUTPUT} -- {b.total} options across {len(b.surfaces)} surfaces')
        return 0

    print(f'behaviour parity: {b.total} options not yet acted on, across {len(b.surfaces)} surfaces'
          f'; {len(b.partial)} partial')
    if not args.check:
        print(md)
        return 0

    failures: List[str] = []
    baseline = committed_total(repo_root)
    if baseline is None:
        failures.append(f'{JSON_OUTPUT} is missing or unreadable -- run --write and commit it')
    elif b.total > baseline:
        failures.append(
            f'{b.total} options are accepted but not acted on, up from {baseline}. '
            'An option that is accepted and ignored passes the name and signature gates, '
            'so this is the only check that sees it. Implement it, or say why it had to grow.'
        )
    stale = [
        path.relative_to(repo_root)
        for path, content in ((repo_root / MD_OUTPUT, md), (repo_root / JSON_OUTPUT, js))
        if not path.is_file() or path.read_text(encoding='utf-8') != content
    ]
    if stale and baseline is not None and b.total < baseline:
        # Closing an option is the point of this file. Say that first, so the
        # instruction reads as banking progress rather than as a reprimand.
        print(f'\n{baseline - b.total} option(s) closed since the last commit: {baseline} -> {b.total}.')
    failures += [f'{rel} is out of date -- run --write and commit the result' for rel in stale]

    if failures:
        print(f'\nFAILURES ({len(failures)}):')
        for f in failures:
            print(f'  - {f}')
        print('behaviour parity: FAILED')
        return 1
    if baseline is not None and b.total < baseline:
        print(f'behaviour parity: OK -- down from {baseline} to {b.total}; run --write to bank it')
    else:
        print('behaviour parity: OK')
    return 0


if __name__ == '__main__':
    sys.exit(main())
