"""
Bot Protocols and Configuration for PraisonAI Agents.

Defines the interfaces and configuration for messaging bot implementations.
All implementations live in the ``praisonai-bot`` package (``praisonai_bot.bots``).
Backward-compatible imports: ``from praisonai.bots import Bot`` via wrapper shims.
"""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass
from .protocols import (
    BotProtocol,
    BotMessageProtocol,
    BotUserProtocol,
    BotChannelProtocol,
    BotMessage,
    BotUser,
    BotChannel,
    MessageType,
    ChatCommandInfo,
    ChatCommandProtocol,
    BotOSProtocol,
    ProbeResult,
    HealthResult,
    EmailProtocol,
    EmailInbox,
    SupportsPresentation,
    PresentationRendererProtocol,
    PlatformCapabilities,
    ChannelField,
    ChannelDescriptor,
    WebhookVerifierProtocol,
    CallbackPayloadStoreProtocol,
    InMemoryCallbackPayloadStore,
    GatewayRuntimeSeams,
    SupportsGatewayRuntime,
    GatewayAdapterContractError,
)
from .base import (
    BasePlatformAdapter,
    SendResult,
    SendStatus,
    SendErrorKind,
    classify_send_error,
)
from .presentation import (
    MessagePresentation,
    PresentationBlock,
    PresentationButton,
    PresentationAction,
    SelectOption,
    PresentationLimits,
    ActionType,
    ButtonStyle,
    BlockType,
    adapt_presentation,
    adapt_presentation_with_report,
    DegradedDelivery,
    table_to_markdown,
    chart_to_text,
    register_presentation_renderer,
    get_presentation_renderer,
)
from .interactive import (
    InteractiveContext,
    InteractiveRegistry,
    InteractiveHandler,
    InteractiveAuthorizer,
    encode_action,
    decode_callback,
    create_registry,
    get_registry,
    register_handler,
    unregister_handler,
    make_reply_handler,
    REPLY_NAMESPACE,
)
from .agent_reply import (
    AgentReply,
    TurnCompletion,
    extract_presentation,
    extract_completion,
    append_completion_note,
)
from .format import (
    format_for_dialect,
    escape_markdown_v2,
    markdown_to_slack,
    strip_markdown,
)
from .webhook_filter import (
    WebhookFilter,
    evaluate_webhook_filter,
    resolve_field,
)
from .config import BotConfig, BotOSConfig, DisplayPolicy, resolve_display_policy
from .silence import (
    SILENT_REPLY_TOKEN,
    is_intentional_silence_response,
    classify_final,
    BotLoopPolicy,
    BotLoopGuard,
)
from .failure import (
    FailureReply,
    render_failure_reply,
)
from .admission import (
    IngressDecision,
    resolve_ingress_admission,
)
from .run_status import (
    RunPhase,
    RunStatusController,
    StallState,
    StallWatchdog,
)

__all__ = [
    "BotProtocol",
    "BotMessageProtocol",
    "BotUserProtocol",
    "BotChannelProtocol",
    "BotMessage",
    "BotUser",
    "BotChannel",
    "BotConfig",
    "DisplayPolicy",
    "resolve_display_policy",
    "MessageType",
    "ChatCommandInfo",
    "ChatCommandProtocol",
    "BotOSProtocol",
    "BotOSConfig",
    "ProbeResult",
    "HealthResult",
    "EmailProtocol",
    "EmailInbox",
    "MessagePresentation",
    "PresentationBlock",
    "PresentationButton",
    "PresentationAction",
    "SelectOption",
    "PresentationLimits",
    "SupportsPresentation",
    "ActionType",
    "ButtonStyle",
    "BlockType",
    "adapt_presentation",
    "adapt_presentation_with_report",
    "DegradedDelivery",
    "table_to_markdown",
    "chart_to_text",
    "PresentationRendererProtocol",
    "register_presentation_renderer",
    "get_presentation_renderer",
    "PlatformCapabilities",
    "ChannelField",
    "ChannelDescriptor",
    "WebhookVerifierProtocol",
    "WebhookFilter",
    "evaluate_webhook_filter",
    "resolve_field",
    "CallbackPayloadStoreProtocol",
    "InMemoryCallbackPayloadStore",
    "GatewayRuntimeSeams",
    "SupportsGatewayRuntime",
    "GatewayAdapterContractError",
    "BasePlatformAdapter",
    "SendResult",
    "SendStatus",
    "SendErrorKind",
    "classify_send_error",
    "InteractiveContext",
    "InteractiveRegistry",
    "InteractiveHandler",
    "InteractiveAuthorizer",
    "encode_action",
    "decode_callback",
    "create_registry",
    "get_registry",
    "register_handler",
    "unregister_handler",
    "make_reply_handler",
    "REPLY_NAMESPACE",
    "AgentReply",
    "TurnCompletion",
    "extract_presentation",
    "extract_completion",
    "append_completion_note",
    "format_for_dialect",
    "escape_markdown_v2",
    "markdown_to_slack",
    "strip_markdown",
    "SILENT_REPLY_TOKEN",
    "is_intentional_silence_response",
    "classify_final",
    "BotLoopPolicy",
    "BotLoopGuard",
    "FailureReply",
    "render_failure_reply",
    "IngressDecision",
    "resolve_ingress_admission",
    "RunPhase",
    "RunStatusController",
    "StallState",
    "StallWatchdog",
]
