/**
 * Built-in approval backends for the PraisonAI TypeScript SDK.
 *
 * Python parity: praisonaiagents/approval/backends.py (request/decision
 * shapes from praisonaiagents/approval/protocols.py; the "always" scope
 * suggestion from praisonaiagents/approval/utils.py `build_permission_target`
 * and praisonaiagents/permissions/arity.py `derive_pattern`).
 *
 * - {@link AutoApproveBackend}: always approves (bots, trusted environments).
 * - {@link ConsoleBackend}: interactive terminal prompt (CLI default); plain
 *   ANSI colours instead of Rich markup, with injectable readers for tests.
 * - {@link AgentApproval}: delegates the decision to another AI agent.
 * - {@link CallbackBackend}: wraps a legacy `(toolName, arguments, riskLevel)` callback.
 *
 * Integration with the existing {@link ApprovalManager}: it has no backend
 * slot, only `onApprovalRequest(handler)`, so {@link setApprovalBackend}
 * registers one delegating handler per manager and swaps the backend behind it.
 *
 * `src/hooks/callbacks.ts` already exports `ApprovalRequest`/`ApprovalDecision`
 * with a different (action/risk) shape, so the Python-shaped types here are
 * named `ApprovalBackendRequest`/`ApprovalBackendDecision`.
 */

import { randomUUID } from 'crypto';
import * as fs from 'fs';
import { ApprovalManager, getApprovalManager, type ApprovalHandler, type ToolApprovalRequest } from '../ai/tool-approval';
import { Logger } from '../utils/logger';

// ============================================================================
// Request / decision shapes (Python parity: approval/protocols.py)
// ============================================================================

/** How long an approval decision should be remembered. */
export type ApprovalScope = 'once' | 'session' | 'always';

/**
 * Request for tool-execution approval.
 * Python parity: `ApprovalRequest` (dataclass) in approval/protocols.py.
 */
export interface ApprovalBackendRequest {
  /** Name of the tool requesting approval. */
  toolName: string;
  /** Arguments the tool will be called with. */
  arguments: Record<string, unknown>;
  /** Risk classification (critical / high / medium / low). */
  riskLevel: string;
  /** Name of the agent that triggered the call. */
  agentName?: string | null;
  /** Session identifier for tracking. */
  sessionId?: string | null;
  /** Arbitrary context for backend-specific data (e.g. a rendered `diff`). */
  context?: Record<string, unknown>;
  /** Stable correlation id; auto-generated by {@link approvalRequest}. */
  approvalId?: string;
  /** Reviewer identities allowed to resolve this request (null = anyone). */
  authorizedReviewers?: string[] | null;
  /** Zero-arg predicate returning true while the originating turn is still live. */
  liveness?: (() => boolean) | null;
}

/**
 * Result of an approval request.
 * Python parity: `ApprovalDecision` (dataclass) in approval/protocols.py.
 */
export interface ApprovalBackendDecision {
  approved: boolean;
  reason: string;
  /** Optional replacement arguments (empty = use originals). */
  modifiedArgs: Record<string, unknown>;
  /** Who/what approved (user, system, console, agent, ...). */
  approver: string | null;
  metadata: Record<string, unknown>;
  scope: ApprovalScope;
  /** Reusable target/pattern to persist for session/always scopes. */
  scopePattern: string | null;
  /** Free-text guidance supplied when denying ("deny with guidance"). */
  feedback: string | null;
}

/** Fields accepted by {@link approvalRequest}. */
export interface ApprovalRequestInit {
  toolName: string;
  arguments: Record<string, unknown>;
  riskLevel: string;
  agentName?: string | null;
  sessionId?: string | null;
  context?: Record<string, unknown>;
  approvalId?: string;
  authorizedReviewers?: string[] | null;
  liveness?: (() => boolean) | null;
}

/**
 * Build an {@link ApprovalBackendRequest} with the Python dataclass defaults
 * (`approvalId` is generated like Python's `uuid4().hex`).
 */
export function approvalRequest(init: ApprovalRequestInit): Required<ApprovalBackendRequest> {
  const {
    toolName,
    arguments: args,
    riskLevel,
    agentName = null,
    sessionId = null,
    context = {},
    approvalId = randomUUID().replace(/-/g, ''),
    authorizedReviewers = null,
    liveness = null,
  } = init;
  return { toolName, arguments: args, riskLevel, agentName, sessionId, context, approvalId, authorizedReviewers, liveness };
}

/** Fields accepted by {@link approvalDecision}; only `approved` is required. */
export interface ApprovalDecisionInit {
  approved: boolean;
  reason?: string;
  modifiedArgs?: Record<string, unknown>;
  approver?: string | null;
  metadata?: Record<string, unknown>;
  scope?: ApprovalScope;
  scopePattern?: string | null;
  feedback?: string | null;
}

/** Build an {@link ApprovalBackendDecision} with the Python dataclass defaults. */
export function approvalDecision(init: ApprovalDecisionInit): ApprovalBackendDecision {
  const {
    approved,
    reason = '',
    modifiedArgs = {},
    approver = null,
    metadata = {},
    scope = 'once',
    scopePattern = null,
    feedback = null,
  } = init;
  return { approved, reason, modifiedArgs, approver, metadata, scope, scopePattern, feedback };
}

/**
 * Structural contract every approval backend satisfies.
 * Python parity: `ApprovalProtocol` (request_approval / request_approval_sync).
 */
export interface ApprovalBackend {
  requestApproval(request: ApprovalBackendRequest): Promise<ApprovalBackendDecision>;
  requestApprovalSync(request: ApprovalBackendRequest): ApprovalBackendDecision;
}

// ============================================================================
// Permission target + reusable pattern (Python parity: approval/utils.py, permissions/arity.py)
// ============================================================================

/** Tool names that map to a shell-command permission target (`bash:<command>`). */
const SHELL_TOOLS: ReadonlySet<string> = new Set(['execute_command', 'acp_execute_command']);

/** File-mutating tool names -> permission-target prefix for their path. */
const FILE_TOOL_PREFIXES: Readonly<Record<string, string>> = {
  edit_file: 'edit',
  acp_edit_file: 'edit',
  write_file: 'write',
  acp_create_file: 'write',
  delete_file: 'delete',
  acp_delete_file: 'delete',
  move_file: 'move',
  copy_file: 'copy',
};

const COMMAND_KEYS = ['command', 'cmd', 'code', 'query'];
const PATH_KEYS = ['file_path', 'path', 'filename', 'file', 'target', 'filepath', 'src'];

/**
 * Build a permission-store target for a tool call.
 * Python parity: `build_permission_target(tool_name, arguments=None)`.
 * Shell tools -> `bash:<command>`, file tools -> `<edit|write|...>:<path>`,
 * everything else -> `tool:<tool_name>`.
 */
export function buildPermissionTarget(toolName: string, args: Record<string, unknown> | null = null): string {
  const a = args ?? {};
  const firstString = (keys: string[]): string | null => {
    for (const key of keys) {
      const value = a[key];
      if (typeof value === 'string' && value.trim()) return value.trim();
    }
    return null;
  };

  if (SHELL_TOOLS.has(toolName)) {
    const command = firstString(COMMAND_KEYS);
    return command ? `bash:${command}` : `tool:${toolName}`;
  }

  const prefix = FILE_TOOL_PREFIXES[toolName];
  if (prefix !== undefined) {
    const path = firstString(PATH_KEYS);
    return path ? `${prefix}:${path}` : `tool:${toolName}`;
  }

  return `tool:${toolName}`;
}

/**
 * Command -> number of leading tokens to keep as the reusable prefix.
 * Python parity: `ARITY` in permissions/arity.py.
 */
export const ARITY: Readonly<Record<string, number>> = Object.freeze({
  git: 2,
  gh: 2,
  hg: 2,
  svn: 2,
  npm: 2,
  yarn: 2,
  pnpm: 2,
  pip: 2,
  cargo: 2,
  go: 2,
  poetry: 2,
  uv: 2,
  make: 2,
  docker: 2,
  'docker compose': 2,
  kubectl: 2,
  helm: 2,
  python: 2,
  python3: 2,
  pytest: 1,
  ruff: 2,
  apt: 2,
  'apt-get': 2,
  brew: 2,
  systemctl: 2,
});

/** Return the longest meaningful command prefix for `tokens`. Python parity: `prefix(tokens, arity_map=None)`. */
export function commandPrefix(tokens: string[], arityMap: Record<string, number> | null = null): string {
  if (tokens.length === 0) return '';
  const table = arityMap ?? ARITY;
  const keyWordCounts = [...new Set(Object.keys(table).map((k) => k.split(/\s+/).length))].sort((x, y) => y - x);
  for (const n of keyWordCounts) {
    if (n > tokens.length) continue;
    const candidate = tokens.slice(0, n).join(' ');
    if (candidate in table) {
      const keep = Math.min(table[candidate], tokens.length);
      return tokens.slice(0, keep).join(' ');
    }
  }
  return tokens[0];
}

const SHELL_OPERATORS = ['&&', '||', '|', ';', '&', '$(', '`', '>', '<', '\n'];

/**
 * Derive a reusable glob pattern for a shell approval target.
 * Python parity: `derive_pattern(target, arity_map=None)`. Only `bash:`/`shell:`
 * targets are generalised; a bare single-token command, an existing glob, or a
 * command containing a shell operator is returned unchanged.
 *
 * @example derivePattern('bash:git status -s') === 'bash:git status *'
 */
export function derivePattern(target: string, arityMap: Record<string, number> | null = null): string {
  const matched = ['bash:', 'shell:'].find((p) => target.startsWith(p));
  if (matched === undefined) return target;

  const command = target.slice(matched.length).trim();
  if (!command) return target;
  if (command.includes('*') || command.includes('?')) return target;
  if (SHELL_OPERATORS.some((op) => command.includes(op))) return target;

  const tokens = command.split(/\s+/);
  const cmdPrefix = commandPrefix(tokens, arityMap);
  if (!cmdPrefix) return target;
  if (cmdPrefix.split(' ').length === 1 && cmdPrefix === command) return target;

  return `${matched}${cmdPrefix} *`;
}

/** Return a reusable "always" pattern for `request` (best-effort). Python parity: `_suggest_scope_pattern`. */
export function suggestScopePattern(request: ApprovalBackendRequest): string {
  const target = buildPermissionTarget(request.toolName, request.arguments);
  try {
    return derivePattern(target);
  } catch {
    return target;
  }
}

// ============================================================================
// AutoApproveBackend
// ============================================================================

/**
 * Always approves. Use for bots or trusted unattended environments.
 * Python parity: `AutoApproveBackend`.
 */
export class AutoApproveBackend implements ApprovalBackend {
  async requestApproval(request: ApprovalBackendRequest): Promise<ApprovalBackendDecision> {
    return this.requestApprovalSync(request);
  }

  requestApprovalSync(request: ApprovalBackendRequest): ApprovalBackendDecision {
    void request;
    return approvalDecision({ approved: true, reason: 'auto-approved', approver: 'system' });
  }
}

// ============================================================================
// ConsoleBackend
// ============================================================================

/** Options for {@link ConsoleBackend} (all optional; Python's class takes none). */
export interface ConsoleBackendOptions {
  /** Input stream for the default async reader (default: process.stdin). */
  input?: NodeJS.ReadableStream;
  /** Output stream for prompts (default: process.stdout). */
  output?: NodeJS.WritableStream;
  /** Injected async reader: receives the question, resolves the raw answer. */
  reader?: (question: string) => Promise<string>;
  /** Injected sync reader for `requestApprovalSync`. */
  syncReader?: (question: string) => string;
  /** Force ANSI colours on/off (default: on when the output is a TTY and NO_COLOR is unset). */
  colors?: boolean;
}

/** `(approved, scope, scopePattern, feedback)` as returned by Python's `_prompt_user`. */
export type ConsolePromptResult = [boolean, ApprovalScope, string | null, string | null];

const ANSI = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
  red: '\x1b[31m',
  boldRed: '\x1b[1;31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m',
  white: '\x1b[37m',
} as const;

type AnsiName = keyof typeof ANSI;

const RISK_COLORS: Readonly<Record<string, AnsiName>> = {
  critical: 'boldRed',
  high: 'red',
  medium: 'yellow',
  low: 'blue',
};

function paint(text: string, color: AnsiName, enabled: boolean): string {
  return enabled ? `${ANSI[color]}${text}${ANSI.reset}` : text;
}

type ChoiceOutcome =
  | { kind: 'deny' }
  | { kind: 'redirect' }
  | { kind: 'approve'; scope: ApprovalScope; scopePattern: string | null };

/**
 * Interactive terminal prompt. Default for CLI usage.
 *
 * Python parity: `ConsoleBackend`. Renders the request (function, risk level,
 * agent, diff or arguments) and asks once / this session / always / no /
 * deny-and-redirect. Plain "y"/"yes" is accepted as "once" and "" defaults to
 * "no", matching the Python prompt default.
 *
 * @example
 * ```typescript
 * const backend = new ConsoleBackend({ reader: async () => 'y' });
 * const decision = await backend.requestApproval(approvalRequest({
 *   toolName: 'execute_command', arguments: { command: 'ls' }, riskLevel: 'low',
 * }));
 * decision.approved; // true
 * ```
 */
export class ConsoleBackend implements ApprovalBackend {
  private readonly input: NodeJS.ReadableStream;
  private readonly output: NodeJS.WritableStream;
  private readonly reader?: (question: string) => Promise<string>;
  private readonly syncReader?: (question: string) => string;
  private readonly colors: boolean;

  constructor(options: ConsoleBackendOptions = {}) {
    this.input = options.input ?? process.stdin;
    this.output = options.output ?? process.stdout;
    this.reader = options.reader;
    this.syncReader = options.syncReader;
    const isTTY = Boolean((this.output as { isTTY?: boolean }).isTTY);
    this.colors = options.colors ?? (isTTY && !process.env.NO_COLOR);
  }

  /**
   * Render a unified diff with coloured +/- hunks, bounded to `maxLines`.
   * Python parity: `_render_diff_markup(diff, max_lines=40)` (ANSI instead of Rich markup).
   */
  static renderDiffMarkup(diff: string, maxLines: number = 40, colors: boolean = true): string {
    const lines = diff.split(/\r?\n/);
    const rendered: string[] = [];
    for (let i = 0; i < lines.length; i++) {
      if (i >= maxLines) {
        rendered.push(paint('... (diff truncated)', 'dim', colors));
        break;
      }
      const line = lines[i];
      if (line.startsWith('+++') || line.startsWith('---')) rendered.push(paint(line, 'bold', colors));
      else if (line.startsWith('@@')) rendered.push(paint(line, 'cyan', colors));
      else if (line.startsWith('+')) rendered.push(paint(line, 'green', colors));
      else if (line.startsWith('-')) rendered.push(paint(line, 'red', colors));
      else rendered.push(paint(line, 'dim', colors));
    }
    return rendered.join('\n') + '\n';
  }

  /** Build the panel text and the choice question for `request`. */
  private buildPrompt(request: ApprovalBackendRequest): { panel: string; question: string; suggested: string } {
    const riskLevel = String(request.riskLevel ?? 'unknown');
    const riskColor: AnsiName = RISK_COLORS[riskLevel] ?? 'white';
    const c = this.colors;

    let toolInfo = `${paint('Function:', 'bold', c)} ${request.toolName}\n`;
    toolInfo += `${paint('Risk Level:', 'bold', c)} ${paint(riskLevel.toUpperCase(), riskColor, c)}\n`;
    if (request.agentName) {
      toolInfo += `${paint('Agent:', 'bold', c)} ${request.agentName}\n`;
    }

    const diff = request.context?.diff;
    if (typeof diff === 'string' && diff) {
      toolInfo += `${paint('Diff:', 'bold', c)}\n`;
      toolInfo += ConsoleBackend.renderDiffMarkup(diff, 40, c);
    } else {
      toolInfo += `${paint('Arguments:', 'bold', c)}\n`;
      for (const [key, value] of Object.entries(request.arguments ?? {})) {
        let strValue = typeof value === 'string' ? value : JSON.stringify(value);
        if (strValue === undefined) strValue = String(value);
        if (strValue.length > 100) strValue = strValue.slice(0, 97) + '...';
        toolInfo += `  ${key}: ${strValue}\n`;
      }
    }

    const rule = paint('─'.repeat(60), riskColor, c);
    const panel =
      `\n${rule}\n${paint('🔒 Tool Approval Required', 'bold', c)}\n${rule}\n` + `${toolInfo.trimEnd()}\n${rule}\n`;

    const suggested = suggestScopePattern(request);
    const alwaysLabel = suggested ? `always (${suggested})` : 'always';
    const question =
      `${paint(`Allow ${request.toolName}?`, riskColor, c)}  ` +
      `[o] once   [s] this session   [a] ${alwaysLabel}   [n] no   [d] deny & redirect\n` +
      `Choice [o/s/a/n/d] (n): `;
    return { panel, question, suggested };
  }

  /** Map a raw answer to an outcome; unknown answers fall back to the "n" default. */
  private interpret(answer: string, suggested: string): ChoiceOutcome {
    const choice = (answer ?? '').trim().toLowerCase();
    switch (choice) {
      case 'o':
      case 'once':
      case 'y':
      case 'yes':
        return { kind: 'approve', scope: 'once', scopePattern: null };
      case 's':
      case 'session':
        return { kind: 'approve', scope: 'session', scopePattern: null };
      case 'a':
      case 'always':
        return { kind: 'approve', scope: 'always', scopePattern: suggested || null };
      case 'd':
      case 'deny':
      case 'redirect':
        return { kind: 'redirect' };
      default:
        return { kind: 'deny' };
    }
  }

  private write(text: string): void {
    this.output.write(text);
  }

  /** Ask one question with the injected reader or a readline interface. */
  private async ask(question: string): Promise<string> {
    if (this.reader) return this.reader(question);
    const readline = await import('readline');
    const rl = readline.createInterface({ input: this.input, output: this.output });
    return new Promise<string>((resolve, reject) => {
      let settled = false;
      rl.once('close', () => {
        // `rl.close()` fires this synchronously; only a genuine EOF (close
        // before any answer) should reject.
        if (!settled) reject(new Error('EOF'));
      });
      rl.question(question, (answer) => {
        settled = true;
        resolve(answer);
        rl.close();
      });
    });
  }

  /** Ask one question synchronously with the injected reader or a blocking stdin read. */
  private askSync(question: string): string {
    if (this.syncReader) return this.syncReader(question);
    if (this.input !== process.stdin) {
      throw new Error('ConsoleBackend.requestApprovalSync needs a syncReader when input is not process.stdin');
    }
    this.write(question);
    const buf = Buffer.alloc(1);
    let line = '';
    for (;;) {
      let n: number;
      try {
        n = fs.readSync(0, buf, 0, 1, null);
      } catch (err) {
        if ((err as NodeJS.ErrnoException).code === 'EAGAIN') continue;
        throw err;
      }
      if (n === 0) {
        if (!line) throw new Error('EOF');
        break;
      }
      const ch = buf.toString('utf8');
      if (ch === '\n') break;
      line += ch;
    }
    return line.replace(/\r$/, '');
  }

  /**
   * Show the panel and ask once/session/always/no/deny-with-guidance.
   * Python parity: `_prompt_user(request)`; resolves
   * `[approved, scope, scopePattern, feedback]`.
   */
  async promptUser(request: ApprovalBackendRequest): Promise<ConsolePromptResult> {
    const { panel, question, suggested } = this.buildPrompt(request);
    this.write(panel);

    let answer: string;
    try {
      answer = await this.ask(question);
    } catch {
      return [false, 'once', null, null];
    }
    const outcome = this.interpret(answer, suggested);
    if (outcome.kind === 'deny') return [false, 'once', null, null];
    if (outcome.kind === 'redirect') {
      let feedback = '';
      try {
        feedback = (await this.ask('What should the agent do instead? ')).trim();
      } catch {
        feedback = '';
      }
      return [false, 'once', null, feedback || null];
    }
    return [true, outcome.scope, outcome.scopePattern, null];
  }

  /** Synchronous twin of {@link promptUser}. */
  promptUserSync(request: ApprovalBackendRequest): ConsolePromptResult {
    const { panel, question, suggested } = this.buildPrompt(request);
    this.write(panel);

    let answer: string;
    try {
      answer = this.askSync(question);
    } catch {
      return [false, 'once', null, null];
    }
    const outcome = this.interpret(answer, suggested);
    if (outcome.kind === 'deny') return [false, 'once', null, null];
    if (outcome.kind === 'redirect') {
      let feedback = '';
      try {
        feedback = this.askSync('What should the agent do instead? ').trim();
      } catch {
        feedback = '';
      }
      return [false, 'once', null, feedback || null];
    }
    return [true, outcome.scope, outcome.scopePattern, null];
  }

  private static toDecision([approved, scope, scopePattern, feedback]: ConsolePromptResult): ApprovalBackendDecision {
    if (approved) {
      return approvalDecision({
        approved: true,
        reason: `User approved (${scope})`,
        approver: 'console',
        scope,
        scopePattern,
      });
    }
    return approvalDecision({
      approved: false,
      reason: feedback ? `User denied: ${feedback}` : 'User denied',
      approver: 'console',
      feedback,
    });
  }

  /** Synchronous approval via the console prompt. */
  requestApprovalSync(request: ApprovalBackendRequest): ApprovalBackendDecision {
    try {
      return ConsoleBackend.toDecision(this.promptUserSync(request));
    } catch (e) {
      void Logger.error(`Console approval error: ${(e as Error).message ?? e}`);
      return approvalDecision({ approved: false, reason: `Approval error: ${(e as Error).message ?? e}` });
    }
  }

  /** Async approval via the console prompt. */
  async requestApproval(request: ApprovalBackendRequest): Promise<ApprovalBackendDecision> {
    try {
      return ConsoleBackend.toDecision(await this.promptUser(request));
    } catch (e) {
      void Logger.error(`Console approval error: ${(e as Error).message ?? e}`);
      return approvalDecision({ approved: false, reason: `Approval error: ${(e as Error).message ?? e}` });
    }
  }
}

// ============================================================================
// AgentApproval
// ============================================================================

/** Duck-typed approver: anything with `achat` or `chat`. */
export interface ApproverAgentLike {
  name?: string;
  achat?: (prompt: string) => Promise<unknown>;
  chat?: (prompt: string) => unknown | Promise<unknown>;
}

/**
 * Delegates approval decisions to another AI agent.
 *
 * Python parity: `AgentApproval(approver_agent=None, llm="gpt-4o-mini")`. The
 * approver receives a structured prompt and answers APPROVE or DENY. Without
 * an approver a default reviewer `Agent` is created lazily.
 *
 * `requestApprovalSync` cannot block on the event loop in JavaScript; it
 * returns a denial whose reason says to use `requestApproval` (Python's
 * error path also resolves to a denial with a reason).
 */
export class AgentApproval implements ApprovalBackend {
  private approverAgent: ApproverAgentLike | null;
  private readonly llm: string;

  constructor(approverAgent: ApproverAgentLike | null = null, llm: string = 'gpt-4o-mini') {
    this.approverAgent = approverAgent;
    this.llm = llm;
  }

  toString(): string {
    const name = this.approverAgent?.name || 'default';
    return `AgentApproval(approver=${JSON.stringify(name)})`;
  }

  /** Lazily create or return the approver agent. Python parity: `_get_approver`. */
  protected async getApprover(): Promise<ApproverAgentLike> {
    if (this.approverAgent !== null) return this.approverAgent;
    const { Agent } = await import('../agent/simple');
    this.approverAgent = new Agent({
      name: 'approval-reviewer',
      instructions:
        'You are a security reviewer for tool execution requests. ' +
        'Evaluate each request and respond with exactly one word: ' +
        'APPROVE or DENY. Consider the tool name, arguments, and risk level. ' +
        'Deny anything that looks destructive, dangerous, or unauthorized. ' +
        'Approve safe read-only operations.',
      llm: this.llm,
    }) as unknown as ApproverAgentLike;
    return this.approverAgent;
  }

  /** Build the evaluation prompt for the approver agent. Python parity: `_build_prompt`. */
  protected buildPrompt(request: ApprovalBackendRequest): string {
    const entries = Object.entries(request.arguments ?? {});
    const argsStr = entries.length
      ? entries.map(([k, v]) => `  ${k}: ${typeof v === 'string' ? v : JSON.stringify(v)}`).join('\n')
      : '  (none)';
    return (
      'Tool Approval Request:\n' +
      `  Tool: ${request.toolName}\n` +
      `  Risk Level: ${String(request.riskLevel).toUpperCase()}\n` +
      `  Agent: ${request.agentName || 'unknown'}\n` +
      `  Arguments:\n${argsStr}\n\n` +
      'Respond with exactly one word: APPROVE or DENY'
    );
  }

  /** Ask the approver agent to evaluate the request. */
  async requestApproval(request: ApprovalBackendRequest): Promise<ApprovalBackendDecision> {
    try {
      const approver = await this.getApprover();
      const prompt = this.buildPrompt(request);

      let response: unknown;
      if (typeof approver.achat === 'function') {
        response = await approver.achat(prompt);
      } else if (typeof approver.chat === 'function') {
        response = await approver.chat(prompt);
      } else {
        return approvalDecision({ approved: false, reason: 'Approver agent has no chat method' });
      }

      const text = String(response).trim();
      const upper = text.toUpperCase();
      const approved = upper.includes('APPROVE') && !upper.includes('DENY');
      return approvalDecision({
        approved,
        reason: `Agent ${approved ? 'approved' : 'denied'}: ${text.slice(0, 200)}`,
        approver: approver.name ?? 'agent',
        metadata: { platform: 'agent', response: text.slice(0, 500) },
      });
    } catch (e) {
      void Logger.error(`AgentApproval error: ${(e as Error).message ?? e}`);
      return approvalDecision({ approved: false, reason: `Agent approval error: ${(e as Error).message ?? e}` });
    }
  }

  /** Not supported synchronously in JavaScript; resolves to a denial explaining why. */
  requestApprovalSync(request: ApprovalBackendRequest): ApprovalBackendDecision {
    void request;
    return approvalDecision({
      approved: false,
      reason: 'Agent approval error: requestApprovalSync cannot block on the event loop; use requestApproval()',
    });
  }
}

// ============================================================================
// CallbackBackend
// ============================================================================

/** Legacy `(functionName, arguments, riskLevel)` approval callback. */
export type LegacyApprovalCallback = (
  functionName: string,
  args: Record<string, unknown>,
  riskLevel: string,
) => ApprovalBackendDecision | boolean | unknown | Promise<ApprovalBackendDecision | boolean | unknown>;

function isDecision(value: unknown): value is ApprovalBackendDecision {
  return typeof value === 'object' && value !== null && typeof (value as ApprovalBackendDecision).approved === 'boolean'
    && 'reason' in (value as object);
}

/** Object carrying an explicit boolean `approved` field (may omit `reason`). */
function hasApprovedField(value: unknown): value is Partial<ApprovalBackendDecision> & { approved: boolean } {
  return typeof value === 'object' && value !== null
    && typeof (value as { approved?: unknown }).approved === 'boolean';
}

function coerceDecision(result: unknown): ApprovalBackendDecision {
  if (isDecision(result)) return result;
  // A partial decision such as `{ approved: false }` must stay a denial:
  // normalise it through approvalDecision rather than falling through to the
  // truthiness path below (a non-empty object is truthy, which would flip it).
  if (hasApprovedField(result)) return approvalDecision({ ...result });
  if (typeof result === 'boolean') return approvalDecision({ approved: result });
  return approvalDecision({ approved: Boolean(result) });
}

/**
 * Wraps a legacy `(functionName, arguments, riskLevel)` callback into an
 * {@link ApprovalBackend}. Python parity: `CallbackBackend(callback)`.
 */
export class CallbackBackend implements ApprovalBackend {
  private readonly callback: LegacyApprovalCallback;

  constructor(callback: LegacyApprovalCallback) {
    this.callback = callback;
  }

  requestApprovalSync(request: ApprovalBackendRequest): ApprovalBackendDecision {
    const result = this.callback(request.toolName, request.arguments, request.riskLevel);
    if (result instanceof Promise) {
      throw new Error('CallbackBackend.requestApprovalSync received a Promise; use requestApproval()');
    }
    return coerceDecision(result);
  }

  async requestApproval(request: ApprovalBackendRequest): Promise<ApprovalBackendDecision> {
    const result = await this.callback(request.toolName, request.arguments, request.riskLevel);
    return coerceDecision(result);
  }
}

// ============================================================================
// ApprovalManager integration
// ============================================================================

/** Options for {@link approvalHandlerFromBackend} / {@link setApprovalBackend}. */
export interface BackendHandlerOptions {
  /** Risk level stamped on requests coming from `ApprovalManager` (it carries none). Default "medium". */
  riskLevel?: string;
  /** Agent name stamped on requests. */
  agentName?: string | null;
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/** Convert an `ApprovalManager` request into the Python-shaped backend request. */
export function toApprovalBackendRequest(
  request: ToolApprovalRequest,
  options: BackendHandlerOptions = {},
): ApprovalBackendRequest {
  const { riskLevel = 'medium', agentName = null } = options;
  return approvalRequest({
    toolName: request.toolName,
    arguments: isPlainObject(request.input) ? request.input : { input: request.input },
    riskLevel,
    agentName,
    context: {
      requestId: request.requestId,
      toolInvocationId: request.toolInvocationId,
      reason: request.reason,
      timestamp: request.timestamp,
    },
  });
}

/** Adapt an {@link ApprovalBackend} into an `ApprovalManager` handler. */
export function approvalHandlerFromBackend(backend: ApprovalBackend, options: BackendHandlerOptions = {}): ApprovalHandler {
  return async (request: ToolApprovalRequest): Promise<boolean> => {
    const decision = await backend.requestApproval(toApprovalBackendRequest(request, options));
    return decision.approved;
  };
}

interface BackendSlot {
  backend: ApprovalBackend | null;
  options: BackendHandlerOptions;
}

const backendSlots = new WeakMap<ApprovalManager, BackendSlot>();

/**
 * Install `backend` as the approval backend of `manager` (default: the global
 * `ApprovalManager`). A single delegating handler is registered per manager
 * the first time; later calls swap the backend behind it. Passing `null`
 * detaches the backend (the handler then declines, so the manager's other
 * handlers or its event flow decide).
 *
 * @example
 * ```typescript
 * setApprovalBackend(new AutoApproveBackend());
 * await getApprovalManager().requestApproval({ toolName: 'rm', input: {} }); // true
 * ```
 */
export function setApprovalBackend(
  backend: ApprovalBackend | null,
  manager: ApprovalManager = getApprovalManager(),
  options: BackendHandlerOptions = {},
): void {
  let slot = backendSlots.get(manager);
  if (!slot) {
    slot = { backend, options };
    backendSlots.set(manager, slot);
    const current = slot;
    manager.onApprovalRequest(async (request: ToolApprovalRequest) => {
      if (!current.backend) return false;
      const decision = await current.backend.requestApproval(toApprovalBackendRequest(request, current.options));
      return decision.approved;
    });
    return;
  }
  slot.backend = backend;
  slot.options = options;
}

/** The approval backend installed on `manager` (default: the global one), or null. */
export function getApprovalBackend(manager: ApprovalManager = getApprovalManager()): ApprovalBackend | null {
  return backendSlots.get(manager)?.backend ?? null;
}
