"""
Example: Auto-save agent output to file

This example demonstrates how to automatically save agent responses to files.
"""

from praisonaiagents import Agent
from praisonaiagents.config import OutputConfig

# Method 1: Simplest - just pass a file path string
agent = Agent(
    instructions="You are a helpful assistant",
    output="output/response.txt"  # Just a string path!
)

# When you call start(), the response is automatically saved
# result = agent.start("Write a short greeting")
# Prints: ✅ Output saved to output/response.txt

# Method 2: With template formatting using OutputConfig
agent_with_template = Agent(
    instructions="You are a blog writer",
    output=OutputConfig(
        output_file="output/blog_post.md",
        template="""# {{title}}

{{content}}

---
*Generated by AI*
"""
    )
)

# The agent will format its response according to the template
# result = agent_with_template.start("Write about Python programming")

# Method 3: Combine with other output settings
agent_verbose = Agent(
    instructions="You are a researcher",
    output=OutputConfig(
        verbose=True,           # Show rich output in terminal
        output_file="output/research.md",  # Also save to file
        template="## Research Summary\n\n{{content}}"
    )
)

print("Examples ready! Uncomment agent.start() calls to run.")
print("Output will be saved to the specified files automatically.")
